### ISSUE TITLE
Do not use EventHandler attribute names as event names

### ISSUE THREAD

**Issue by ddorwin** [w3c/webvr#104]
https://w3c.github.io/webvr/#interface-window defines the event names but uses the `"on..."` names of the EventHandler attributes. The event names don't include `"on"`.

Also, the events are generally defined separately from the EventHandlers. For example, in an Event Summary section, such as https://w3c.github.io/encrypted-media/#mediakeysession-events.

**Comment by cvan** [comment]
thanks, good catch - I've been meaning to fix those (and thoroughly document the events - see #23).

**Comment by toji** [comment]
Events are better defined in the latest spec. Closing.
