### ISSUE TITLE
Add "requested" reason to VRDisplayEventReason

### ISSUE THREAD

**Issue by kearwood** [w3c/webvr#106]
In order to provide a streamlined user experience, we would like to add an "Enter VR Button"-like option to the browser chrome in Firefox.  The benefits to the end user include not having to search for the option within a page and being able to assign this to a physical keyboard or controller button that works in any site consistently.

When the user requests to "Enter VR" with the browser itself, I propose that onvrdisplayactivate is triggered by the browser with a reason code such as "requested" to allow the content to (optionally) respond to this event.

**Comment by dmarcos** [comment]
This is an excellent idea.

**Comment by spite** [comment]
Agreed! I added an "Activate HMD" button in the Chrome WebVR extension, that emulates a ```vrdisplayactivate```/```vrdisplaydeactivate``` (so it relies on the page listening to those events), and it's very useful, specially when the "Enter VR" button is in different places depending on the page. 

That new button feature could even detect if there's code calling the WebVR API and be enabled or not.

**Comment by toji** [comment]
+1, I really like this idea. Not sure that `requested` really captures the concept, but I'm fine with it if we don't come up with anything clearer.
