### ISSUE TITLE
Decide on a medium for consolidating spec conversations

### ISSUE THREAD

**Issue by cvan** [w3c/webvr#110]
- [W3C WebVR Community Group](https://www.w3.org/community/webvr/)'s [`public-webvr` mailing list](https://lists.w3.org/Archives/Public/public-webvr/)
- WebVR's [`web-vr-discuss` mailing list](https://mail.mozilla.org/listinfo/web-vr-discuss)
- [this repo's Issues](https://github.com/w3c/webvr/issues)

**Comment by anssiko** [comment]
My recommendation would be to use this repo's issues for spec discussions. The [Standards on GitHub](https://annevankesteren.nl/2016/10/standards-on-github) blog post by @annevk sums it up nicely.

**Comment by cvan** [comment]
I agree 100%. And, yep, I've read @annevk's post - agreed with that too.

Whichever, we decide, I'll update https://webvr.info/ and other sources accordingly.

Pinging @toji, @kearwood, etc.

**Comment by toji** [comment]
+1 to using this repo's issues for discussion.

**Comment by kearwood** [comment]
+1...  Issues here would work IMHO.

**Comment by cvan** [comment]
Issues, it is.
