### ISSUE TITLE
Spec VR display idleness?

### ISSUE THREAD

**Issue by cvan** [w3c/webvr#113]

**Comment by caseyyee** [comment]
What you mean by _idleness_?   Is this for cases when users 

Is this not covered already by the events for headset mounted and unmounted? 

Though, I can see a case for this for headsets that do not have a presence sensor.

**Comment by caseyyee** [comment]
What do you mean by _idleness_?  Is this for when the headset is not being worn?   Won't this be accounted for by the headset mounted and unmounted events?    I suppose that there will be cases where headsets don't have a face sensor that need to be accounted for as well.

**Comment by toji** [comment]
I'm confused on what this means as well, and given that there hasn't been any followup I'm gonna close it to reduce noise on the issue tracker. Feel free to re-open with clarification if needed.

**Comment by cvan** [comment]
For context, I filed and suggested this feature because in the OpenVR API there's a way to [get the HMD's current state](https://github.com/ValveSoftware/openvr/blob/7fa6470/headers/openvr.h#L1308-L1309):

* [unknown](https://github.com/ValveSoftware/openvr/blob/7fa6470/headers/openvr.h#L591)
* [idle](https://github.com/ValveSoftware/openvr/blob/7fa6470/headers/openvr.h#L592)
* [active](https://github.com/ValveSoftware/openvr/blob/7fa6470/headers/openvr.h#L593)
* [active but timed out](https://github.com/ValveSoftware/openvr/blob/7fa6470/headers/openvr.h#L594)
* [standby](https://github.com/ValveSoftware/openvr/blob/7fa6470/headers/openvr.h#L595)
