### ISSUE TITLE
IRC and mailing list

### ISSUE THREAD

**Issue by NavidZ** [w3c/webvr#129]
@cvan @toji 
Some other specs have these information in their participation section at the beginning of the spec. I found irc.w3.org#webvr and Mozilla and W3C mailing lists . But I wasn't sure which one was the way you guys collaborate mostly on this spec. If someone can confirm I can join and create a PR as well.

**Comment by cvan** [comment]
There is a Communication section I added to the README: https://github.com/w3c/webvr/blob/master/README.md#communication We can add that to the Bikeshed doc too - good call. If IRC is preferred by folks, which server? Freenode? Thanks for filing.

**Comment by NavidZ** [comment]
I was wondering which mailing list is the active one. The w3c one (which you have in readme) or Mozilla one (web-vr-discuss@mozilla.org) or both of them are active in their own domain. Regarding the IRC there seems to be one for w3c listed [here](https://www.w3.org/community/webvr/) which was also used during TPAC.

**Comment by liamquin** [comment]
On Sat, 2016-10-22 at 11:26 -0700, chris van wiemeersch wrote:
> [...] If IRC is preferred by folks, which server? Freenode?

Most W3C groups use the W3C IRC server, irc.w3.org
https://www.w3.org/Project/IRC/
