### ISSUE TITLE
VRDisplayEventInit Constructor needs a type argument

### ISSUE THREAD

**Issue by kearwood** [w3c/webvr#130]
The constructor for VRDisplayEventInit is not consistent with other events, which accept a "type" argument:

https://w3c.github.io/webvr/#interface-vrdisplayevent

I propose we change the constructor from:

[Constructor(VRDisplayEventInit eventInitDict)]

To:

[Constructor(DOMString type, VRDisplayEventInit eventInitDict)]

**Comment by toji** [comment]
SGTM. Turns out that's already what I'm doing in Chrome. :P
