### ISSUE TITLE
Constructable VRLayer instead of dictionary?

### ISSUE THREAD

**Issue by bfgeek** [w3c/webvr#142]
How likely is it that there will be different types of VRLayers in the future?

It might make more sense for VRLayer to be constructible directly? e.g.

```js
const fovLayer = new VRFOVLayer({canvas: canvas});
fov.eyeSomethingSomething = something;

const rectLayer = new VRRectLayer({...});
rectLayer.position.m11 = something;

display.requestPresent([fovLayer, rectLayer]);
```

@domenic might have thoughts here.

Ian

**Comment by domenic** [comment]
As far as I can tell it's already constructible.

**Comment by bfgeek** [comment]
Oh, I must have been looking at an old version of the spec in my browser, `requestPresent` seems broken then? @toji

**Comment by toji** [comment]
Going to close this as a duplicate of #107, and note that a solution has been proposed in #186
