### ISSUE TITLE
webvr not working with oculus rift cv1

### ISSUE THREAD

**Issue by aearanky** [w3c/webvr#148]
I am facing this issue:
Oculus consumer version cv1 and
here is my config:
Windows 10,
Oculus Platform Runtime SDK 1.9
Chromimum build from https://webvr.info/get-chrome/ Oct 29th, Web
webvr flag set in the chromium browser
"unknown source allowed" in oculus

Tried the same on firefox developer edition.

when i navigate to https://toji.github.io/webvr-samples/02-stereo-rendering.html
I can see the browser detecting the HMD, and rendering moves in the browser as i move my rift around.

But when i try to view this experience inside my oculus it always shows message:
"Sorry chrome.exe is taking a while to load."

Can someone please post a solution?

**Comment by ssylvan** [comment]
Does the 03 sample work (the VR Presentation one)? If that doesn't work, then one of the chrome guys will have to help.

That particular Oculus message shows up when nothing is presenting to the HMD. I'm pretty sure the 02 sample does not render the VR display (it just demonstrates reading the poses and rendering to the monitor), but the 03 one does render to the VR display.

**Comment by dmarcos** [comment]
I see you filed as well the issue on https://github.com/toji/chrome-webvr-issues/issues/115. It's where it belongs. Let's move the conversation there. I close this issue.
