### ISSUE TITLE
UnityWebGL->WebVR, headset is tracking but not loading to HMD

### ISSUE THREAD

**Issue by uownedd** [w3c/webvr#150]
example upload here: http://christopherlatorres.com/vr/
-
I am using this bridge that was uploaded on github a while back to go from unity to webVR. https://github.com/gtk2k/Unity-WebVR-Assets
-
Upon running in chromium, everything loads and initiliazes fine, and the headset even tracks from the browser. Whenever "Enter VR" is pressed it does not show up in HMD (vive) and displays in console `"submitFrame must be called within a VRDisplay.requestAnimationFrame callback."`
-
The code at that line is:
```
// Post-render callback from Unity. 
window.postRender = function () { 
if (!isDeprecatedAPI && isPresenting()) { 

vrDisplay.submitFrame(vrPose); } };
```

and then the vrPose is

`vrPose = getPose();`

getPose is 

```
function getPose () {
    if (!vrDisplay) {
      return;
    }
    if (isDeprecatedAPI) {
      return vrSensor.getState();
    } else {
      return vrDisplay.getPose();
    }
  }
```
-
Honestly, I'm stumped on how to get this fixed to display in HMD.
Thanks always, long live webVR

**Comment by toji** [comment]
This seems like a Unity integration issue, and not something we can solve here. Sorry!
