### ISSUE TITLE
Move API methods and events to navigator.vr namespace

### ISSUE THREAD

**Issue by cvan** [w3c/webvr#152]
Based on conversations and PR #116 opened by @toji, for v1.2, we intend on moving the current VR interfaces under the `navigator.vr` namespace and emit events on the `VRDisplay` instances instead of on `window`. This is a required change to enable folks to use WebVR in a worker context (where the DOM is inaccessible).

Luckily, although this is a backwards-incompatible change, these new interfaces and events can be easily polyfilled so existing WebVR sites using the current (v1.1) API can drop in a polyfill and use the new interfaces.

It's an implementation matter, but User Agents that have implemented the existing (v1.1) WebVR API interfaces and events should continue to support the old API and events but provide Console warnings to web developers, if possible.

**Comment by toji** [comment]
Closing now that #116 is merged.
