### ISSUE TITLE
Redefine layer bounds to be standard OpenGL texture coords.

### ISSUE THREAD

**Issue by toji** [w3c/webvr#156]
In 1.1 the layer `leftBounds` and `rightBounds` are defined as a kind of strange combination of a UV and a width and height, defined in UV space. It also uses the order [left, top, width, height], which implies a flipped UV space from OpenGL. I've brought this up before and the consensus was generally "Don't break it if we don't have to", but since then I've been bitten by this system a few time and I think that Chrome's implementation has it "upside down" as a result. :P 

I suggest that for clarity in 1.2 we redefine the layer bounds to explicitly be OpenGL UVs with the order [left, bottom, right, top]. (In OpenGL's UV space positive Y is up, so the bottom left corner is the origin.) Additionally we should define that bounds where left > right or bottom > top are invalid.

This means that instead of the default bounds being:
```
{
leftBounds: [0.0, 0.0, 0.5, 1.0],
rightBounds: [0.5, 0.0, 0.5, 1.0]
}
```

They become:
```
{
leftBounds: [0.0, 0.0, 0.5, 1.0],
rightBounds: [0.5, 0.0, 1.0, 1.0]
}
```

This feels more consistent with the rest of the platform to me (sticks to WebGL's conventions) and more predictable for developers. Any complaints?

**Comment by mkeblx** [comment]
This seems quite unobjectionable (and none expressed), and minor. I don't see a reason for not redefining & closing, as we don't care about backwards compat too much and easily polyfillable.

**Comment by toji** [comment]
Pushed this change as d6219a8c3e3dd892be60901937c483b1747bcf43. We're likely redefining how layers work soon, so it's somewhat moot, but I wanted to close the ticket down and ensure than change carried forward.

**Comment by RafaelCintron** [comment]
LGTM after the fact.
