### ISSUE TITLE
Clarify requestPresent outside of user-initiated action

### ISSUE THREAD

**Issue by ssylvan** [w3c/webvr#164]
Currently the spec says "If requestPresent() is called outside of a user gesture the promise MUST be rejected."
However, presumably that only makes sense if we aren't already presenting? In other words, if we're calling requestPresent while already presenting in order to update the layers, shouldn't that be allowed even if it wasn't user-initiated?

**Comment by toji** [comment]
The short answer is yes, the user gesture requirement should only be for the initial requestor went call. We'll review the spec text and make sure this is clear.

**Comment by ssylvan** [comment]
Thanks! I suspected this was the intent but wanted to mak sure.

**Comment by toji** [comment]
Tweaked the spec text in bcf5cbd2e8588b3088204305176c30f2f4a434f1, FWIW. Closing.
