### ISSUE TITLE
VRLayer's leftBounds/rightBounds attributes: Sequences must not be used as the type of an attribute

### ISSUE THREAD

**Issue by ddorwin** [w3c/webvr#166]
The spec currently has:
```
interface VRLayer {
  ...
  readonly **attribute sequence**<float> leftBounds;
  readonly **attribute sequence**<float> rightBounds;
};
```

Per https://heycam.github.io/webidl/#idl-sequence:
>Sequences must not be used as the type of an attribute or constant.
>>Note: This restriction exists so that it is clear to specification writers and API users that sequences are copied rather than having references to them passed around. Instead of a writable attribute of a sequence type, it is suggested that a pair of operations to get and set the sequence is used.

**Comment by toji** [comment]
Closing since this is planned to be addressed in 2.0. If anyone has issues with the 2.0 proposal, please file a new issue. For details see the "VRCanvasLayer" interface described here: https://github.com/w3c/webvr/blob/master/explainer.md#appendix-b-proposed-idl
