### ISSUE TITLE
Feedback: Duplicate requestAnimationFrame API is confusing

### ISSUE THREAD

**Issue by travisleithead** [w3c/webvr#171]
vrDisplay's requestAnimationFrame is attempting to replace window.requestAnimationFrame by having a fallback behavior when presenting vs. not presenting. This makes it a competitive API with window.requestAnimationFrame rather than a dedicated API for specifically for one or more vrDisplays. To eliminate this ambiguity and potential developer confusion, I would recommend two changes:

1. Change the name. Something like `requestVRFrame()`.
2. Remove the fallback behavior. If the vrDisplay is not presenting, there is no need to run this loop. Point developers to the real requestAnimationFrame or other techniques for driving input external to the vrDisplay.

**Comment by toji** [comment]
I've viewed the fallback behavior as a developer convenience, but I'm not too opposed to removing it. As for the name change I felt that it would actually _eliminate_ confusion about what the function did if the name was the same, but I can see the argument for it having the opposite effect. Not the end of the world for me if we want to change it. (And for the record `requestVRFrame()` SGTM)

Would be interested in hearing other implementor's take on this.

**Comment by speigg** [comment]
I think the name `requestAnimationFrame` makes sense. In my mind, the primary requestAnimationFrame is used to drive animation for the primary display, and each external display should likewise have its own requestAnimationFrame. 

I do agree with eliminating the fallback behavior.

**Comment by toji** [comment]
Closing since this is planned to be addressed in 2.0. If anyone has issues with the 2.0 proposal, please file a new issue. For details see: https://github.com/w3c/webvr/blob/master/explainer.md#main-render-loop
