### ISSUE TITLE
Use RFC words more consistently

### ISSUE THREAD

**Issue by ddorwin** [w3c/webvr#172]
The spec contains a mix of lowercase and uppercase RFC words, such as "MUST." These should be uppercase if they are requirements of the spec.

Also, such requirements should probably be phrased as requirements on the user agent. For example, "Trusted UI must be drawn..." should probably be "The user agent MUST draw Trusted UI..." There are other phrasings like "foo will happen" that should probably be converted to a MUST requirements as well.

Some specs specially format RFC words, which highlights the importance. I know ReSpec supports, this but I don't know about the tool used for this spec.

**Comment by toji** [comment]
We use Bikeshed for formatting. Don't know if it supports automatic formatting of RFC words. Definitely need to be more consistent about this, though. Thanks!

**Comment by toji** [comment]
Closing since this applied primarily to 1.1. It will definitely be something we pay closer attention to as we draw up the 2.0 spec language.
