### ISSUE TITLE
Clarify angularVelocity and angularAcceleration

### ISSUE THREAD

**Issue by brianchirls** [w3c/webvr#177]
Is the vector the direction of the axis while the magnitude of the vector is the angle of rotation around that axis? Is positive rotation counter-clockwise?

Or is it something else?

If anybody has any sample code of how to work with these values, that'd be helpful. For example, using angularVelocity to determine the velocity of a child object at given offset from the center of the controller - like if you're swinging a tennis racket and want to know the velocity of the end where you hit the ball.

Thanks.

**Comment by toji** [comment]
Possibly made moot by #185, depending on the outcome of that discussion.

**Comment by klausw** [comment]
See also https://github.com/w3c/webvr/issues/212 , different implementations currently disagree on the reference frame for these vectors.

**Comment by toji** [comment]
#212 is addressed now, and @klausw has helpfully provided some visualizations for the values in the controllers sample. Hopefully that addresses this issue as well.
