### ISSUE TITLE
Rename `VRDisplayCapabilities#canPresent` to be less ambiguous for detecting "magic window"

### ISSUE THREAD

**Issue by cvan** [w3c/webvr#182]
IMO, [`<VRDisplay>.capabilities.canPresent`](https://w3c.github.io/webvr/#dom-vrdisplaycapabilities-canpresent) seems a bit odd (to be a property of the `capabilities` object and the `canPresent` naming).

perhaps instead have `<VRDisplay>.isRealDisplay` (à la OpenVR's [`IsDisplayRealDisplay`](https://github.com/ValveSoftware/openvr/blob/9d48ccf9/headers/openvr_driver.h#L1601-L1602))?

**Comment by toji** [comment]
@cvan knows this, but for the benefit of anyone else: The proposal for 2.0 here is that you attempt to create an exclusive (presenting) or non-exclusive (magic window) context, and the implementation can fail in either case. There's also a `supportsSession` function for testing if the given session type is supported without actually creating one. That should generally solve the issue of this being an awkward capability bit.

**Comment by cvan** [comment]
yeah, this seems good - thanks for the update
