### ISSUE TITLE
Remove resetPose, add event for detecting system-triggered reset

### ISSUE THREAD

**Issue by toji** [w3c/webvr#189]
I've had a conversation with a few people about this, but just now realized that there hasn't been a formal issue logged for it: I feel pretty strongly that we should remove the ability for applications to programatically reset the pose from the next iteration of the API. There's a few reasons for this:

- Not all platforms support the ability to programatically reset. (Daydream is one example)
- On platforms where a programmatic reset is available you end up in an awkward situation where one page may be able to force a state change in another page or, even worse, other applications.
- Resetting responds differently on different platforms, and may even differ on the same device depending on the mode it's in. (Room scale vs. sitting)
- Most (all?) major VR platforms have a way to allow the user to reset the pose via a gesture or system UI.
- Resetting can easily be handled completely in-app by storing an inverse matrix of the current pose and multiplying future pose matrices against it, which ultimately gives the application more consistent behavior and greater control.

That being said, I do feel it's worthwhile to notify the application when a system-level reset has occurred, since applications can take advantage of the tracking discontinuity it creates to accomplish certain effects, like repositioning the user or UI elements more logically or resetting the aforementioned inverse matrices.

**Comment by NellWaliczek** [comment]
Perhaps we can incorporate this notion of system-level reset alongside the notions of tracking loss?

**Comment by RafaelCintron** [comment]
I am in favor of removing the notion of "resetting" pose along with exposing events for tracking loss.  With the recent round of frame of reference proposals flying around, developers should be able to accomplish the same thing by simply creating new frame of reference object instances.

**Comment by toji** [comment]
Closing since this appears to have broad agreement. `resetPose` does not appear in the 2.0 explainer but a `resetpose` event is available on the session to detect system-level resets.
