### ISSUE TITLE
Resolve name conflicts between 1.1 and 2.0

### ISSUE THREAD

**Issue by toji** [w3c/webvr#192]
It seems like there's a non-zero chance that some browser will be exposing the 1.1 and 2.0 versions of the API simultaneously for some period of time. If this is true, we need to be careful about not having conflicting interface names that have different functionality.

There's two ways we could handle this. The "safest" is to make sure all the interface names in 2.0 are different than 1.1. This isn't too hard, but may mean abandoning a name or two that people feel is particularly fitting. My suggestions for this approach would be:

| 1.1                  | 2.0                |
| ------------- |-------------|
| VRDisplay      | VRDevice    |
| VRLayer      | VRCompositorLayer      |
| VRDisplayEvent | VREvent      |
| VRFrameData | VRDevicePose |

Worth nothing that since previously the VRLayer was just a dictionary, though, we may not need to change it.

Alternatively, we could retroactively change some of the 1.1 interface names. This carries with it a small compatibility risk in case anybody has code that's looking for `typeof(object) == name`. (Three.js does a tiny bit of this, but only against `VRFrameData`), but overall it probably won't cause widespread issues.

**Comment by AlbertoElias** [comment]
Wasn't the reason behind using an Origin trial to signal that it's experimental and will break so we can use current names? Origin trials have a max date, so sites will stop working anyway

**Comment by toji** [comment]
Chrome is doing an Origin Trial, yes, but other browsers which don't have similar mechanisms have signaled that they are comfortable making the current form of the API available by default and then later deprecate it when the revised API is ready. This would presumably lead to a period where both forms of the API are available on a browser in tandem.

**Comment by slightlyoff** [comment]
It is a pretty bad smell if there is compat concern at this point when all participants are shipping auto-updating implementations and have committed to changing their implementations quickly. It indicates that there are more users than anticipated. Do any of the teams that have shipped have numbers about overall usage?

**Comment by toji** [comment]
It seems that Mozilla at least has plans to have both versions of the API available in their browser simultaneously, so some care should be taken to avoid interface name collisions.

**Comment by toji** [comment]
Follow up to this: I'm happy with `VRDisplay`->`VRDevice` (which is technically a revert of a pre-1.0 change) and `VRFrameData`->`VRDevicePose` for the sake of avoiding conflicts. Following from that and the discussion in #191 the events become `VRDeviceEvent` and `VRSessionEvent`, which is already nicely disambiguated.

I am reluctant to change `VRLayer`, though, since it's concise, descriptive, and easily understood. I would propose that for that interface, since the previous version was a dictionary, we instead keep `VRLayer` for 2.0 and change the 1.1 spec to something like `VRLayerInit`. This should cause zero compatibility issues, doesn't force a compromise on the name, and allows a browser to support both version of the API simultaneously if they choose. (And doesn't cause issues with polyfills.)

Leaving this open for a bit to field opinions (Wouldn't mind hearing @bzbarsky's opinion especially) but if there's no active dissent I'll make the changes to both the explainer and 1.1 API and close it up.

**Comment by toji** [comment]
Given the resounding lack of concerned feedback, I've made the above adjustments in 61099519fb732067b7ba29ccde41a3bc279712a2.
