### ISSUE TITLE
Why is VRFrameData something the _caller_ allocates?

### ISSUE THREAD

**Issue by bzbarsky** [w3c/webvr#196]
The only thing it's used for is calling `https://w3c.github.io/webvr/archive/prerelease/1.1/#dom-vrdisplay-getframedata`, so why can't `getFrameData()` just return a `VRFrameData` object?  Is the idea to reduce the amount of allocation?  But then why is `getPose()` allocating a new thing each time?

**Comment by mkeblx** [comment]
Yes GC. See https://github.com/w3c/webvr/issues/128.

`getPose` is deprecated, the same `VRPose` data will be available in `VRFrameData`.

**Comment by toji** [comment]
As @mkeblx pointed out, this is effectively a dup of #128 so I'm going to close it. It's definitely been a point of contention, though, and we need to come to a resolution that everyone is happy with in the upcoming spec revision.

**Comment by bzbarsky** [comment]
I think what you should really do is have a Note in the spec explaining the setup so people don't get confused.

Especially because the one implementation I've looked at may not allocate a new VRFrameData object, but does allocate new objects for all its properties when getFrameData is called, so you get approximately 0 benefit in terms of avoiding GC.
