### ISSUE TITLE
Clarify angular velocity

### ISSUE THREAD

**Issue by klausw** [w3c/webvr#212]
Currently, both 1.1 and 2.0 have this definition:

*angularVelocity* Angular velocity of the sensor given in radians per second. MAY be null if the sensor is incapable of providing angular velocity. When not null MUST be a three-element array.

The "position" section specifies a coordinate system, but I think it's a bit underspecified if this equally applies for velocities and accelerations or if those use a sensor local frame of reference. 

(Edited: originally I proposed using sensor-relative here, but I changed it to assume seated-relative since that's the current Chromium/Vive implementation's behavior.)

How about adding something like this to the spec or explainer, assuming that seated-relative is the intended interpretation?

> The angular velocity is a 3-element vector with magnitude equal to the rotation speed in radians/second, pointing along the rotation axis in the sitting frame of reference, using right-hand rule for direction. Linear velocity and acceleration vectors also use the sitting frame of reference.
> 
> For example, linear acceleration for a resting controller on Earth will always be reported as a "1g acceleration towards +Y" (0, 9.81 m/s^2, 0) vector, independently of how the controller itself is oriented.
> 
> Examples for a headset sensor, if looking along the seated position's -Z axis with +Y up:
> - "look up" motion: (positive, 0, 0)
> - "turn left" motion: (0, positive, 0)
> - "lean head left" motion: (0, 0, positive)
>
> After turning 90 degrees right, facing towards the seated coordinate system's +X axis:
> - "look up" motion: (0, 0, positive)
> - "turn left" motion: (0, positive, 0)
> - "lean head left" motion: (negative, 0, 0)
>
> You must apply appropriate rotations if you want sensor-relative or standing-space (roomscale) vectors.

How do other implementations behave here? I've implemented a debug view which I think looks correct for this interpretation and the Chromium/Vive implementation: https://klausw.github.io/webvr.info/samples/XX-vr-controllers.html

Chrome with a Daydream View controller is *not* consistent with this, it reports sensor-relative angular velocity.

**Comment by klausw** [comment]
For comparison, GVR and OpenVR appear to report velocities in a sensor-local frame through their native APIs:

https://developers.google.com/vr/unity/reference/class/gvr-controller

https://github.com/ValveSoftware/openvr/blob/7fa6470f2972970859f2395f1390f6d87d4b0fc3/headers/openvr_driver.h#L185

**Comment by klausw** [comment]
Correction, apparently high-level OpenVR uses global reference frame for angular velocity.

Anyway, I don't really have a strong preference for this, just want to be clear which one it is.

**Comment by klausw** [comment]
Hm, looks like we already have an inconsistency.

I modified the XX-vr-controller sample to show controller-relative coordinate axes and the angular velocity vector in those coordinates: https://klausw.github.io/webvr.info/samples/XX-vr-controllers.html

On Chrome for Android with a Daydream controller, the angular velocity is controller relative, so the matches controller motion independent of the overall controller orientation.

When using @toji's Chrome for Windows build on a Vive, the angular velocity vector is absolute, so the arrow only matches motion when facing the neutral orientation.

I don't have a strong preference how this should work, but we should make sure implementations agree on it.

Side note, both of them don't seem to provide linear acceleration unless I'm misreading it. I get an array with constant [0, 0, 0] for the Daydream controller.

**Comment by klausw** [comment]
For anyone following via e-mail, please re-read the original post and followups which I've edited. I'm increasingly convinced that the intended interpretation is to have all vectors use seated reference frame, this matches the current behavior of the Chromium build with HTC Vive. Does that sound right?

**Comment by klausw** [comment]
I've collected some more data on how the angular velocity is reported for both headset and controllers. It looks as if the current implementations just provide whatever the native API provides, so it's rather messy:

Browser | Device | Headset | Controller
----- | ----- | ----- | -----
Firefox Nightly | HTC Vive | Seated | Seated
Chromium | HTC Vive | Seated | Seated
Firefox Nightly | Oculus Rift | Sensor relative | Sensor relative
Chromium | Oculus Rift | Sensor relative | Sensor relative
Chrome | Daydream | (not reported) | Sensor relative

**Comment by RafaelCintron** [comment]
When you use Windows Mixed Reality (formerly Windows Holographic), you create a [SpatialLocator](https://docs.microsoft.com/en-us/uwp/api/windows.perception.spatial.spatiallocator) object from the `HolographicDisplay` object. With the spatial locator, you create frame of references which has an accompanying coordinate system object.  With the coordinate system object, you can you can call TryLocateAtTimeStamp, which will give you a [SpatialLocation](https://docs.microsoft.com/en-us/uwp/api/windows.perception.spatial.spatiallocation).  The spatial location has the accompanying angular and linear acceleration and velocities.  

Since the WebVR V2 APIs have the concept of coordinate systems and frame of references, we should be able to spec things such that the developer can ask for the velocities and accelerations in any coordinate system they please.

**Comment by klausw** [comment]
In today's discussion in the implementer's forum, it sounded that there weren't any objections to picking a standard reference frame for the implementations that opt to expose this data, but please let me know if you do have concerns for this. For consistency with the existing WebVR 1.1 spec which specifies that positions use a sitting reference frame and the gamepad API extensions which also define a coordinate system only for position, I think it would be least confusing to use this frame for the angular velocity or acceleration vectors also.

@kearwood , would you be willing to go along with this for Firefox and transform the Oculus sensor vectors into sitting space? The current controller orientation basically rotates the sensor's (0, 0, -1) forward direction to the pad's corresponding forward direction in sitting space, so you can just use that to rotate the sensor-space angular velocity into sitting space. Something like this (from the code I'm adding for the Daydream controller transform):

```
  Mat4f pose_mat = QuatToMatrix(pad.orientation);
  pad.accel = MatrixVectorMul(pose_mat, controller_state_->GetAccel());
  pad.gyro = MatrixVectorMul(pose_mat, controller_state_->GetGyro());
```

@DigiTec and @Artyom17, any concerns from Oculus's side? This of course doesn't need any changes on the part of your native APIs (though I would recommend being more specific in your [documentation](https://developer3.oculus.com/doc/1.12-libovr/structovr_pose_statef.html#ac300f937fa19376ead5e0edbecf68fbb) regarding its semantics), but it could affect existing content on these platforms if existing browsers change the frame of reference. Are you currently exposing angular velocity or other vectors in Carmel?

**Comment by klausw** [comment]
This is still open, so far I haven't heard clear preferences from others one way or another.

There is one potential benefit to using sensor-relative coordinates. A gamepad device coul include an accelerometer/gyro but no direct way to measure orientation. In this case this device could easily report the measured vectors in its native sensor-relative space, but converting them to sitting space may not be feasible or may introduce inaccuracies.

**Comment by RafaelCintron** [comment]
For WebVR 2.0, I think all data returned by `getDevicePose` should be in the coordinate system passed into `getDevicePose`. By the same token, coordinate systems should a part of the new spatial input mechanism we've been talking about for gamepad-like objects. 

For WebVR v1.1, I am fine with using the sitting coordinate system for both `getFrameData` as well as the `GamepadPose` returned through the gamepad API.

**Comment by toji** [comment]
It seems as though most people here aren't very opinionated when it comes to WebVR 1.1, and it's still an open question of if 2.0 will include these values at all, though if they do it should definitely be better specified and probably follow Rafael's suggestion of using explicit coordinate systems.

I've made changes to the 1.1 spec to account for this.
