### ISSUE TITLE
Move depthNear/Far to VRCoordinateSystem or VRFrameOfReference

### ISSUE THREAD

**Issue by toji** [w3c/webvr#213]
For a while now the presence of depthNear and depthFar on the VRSession has been gnawing at me because they felt out of place, and there's been questions in the past about their exact behavior. (#120) Specifically, what's the expected result of this:

```js
session.depthFar = 10;
let poseA = session.getPose(coordSystem);
session.depthFar = 100;
let poseB = session.getPose(coordSystem);
```

In that scenario it seems like `poseA` and `poseB` should return different projection matrices, but that conflicts with the idea that the pose returned should stay the same throughout the duration of the frame callback.

To resolve that (and clean up the session interface a bit) I propose that we make the depth parameters const members of either the `VRCoordinateSystem` or the `VRFrameOfReference` (and I'd love @NellWaliczek or @RafaelCintron's advice on which of those seems more appropriate.) The code would look like this:

```js
let frameOfRef = await vrSession.createFrameOfReference({
    type: "EyeLevel",
    depthNear: 0.1,
    depthFar: 10 });

let poseA = session.getPose(frameOfRef);
frameOfRef.depthFar = 100; // ERROR! Read only member!
```

This enforces that the same Frame of Reference always returns the same pose for the duration of the frame callback. Making `createFrameOfReference` take a dictionary also allows us to provide sensible defaults for everything (including `type`?) and makes it more extensible in the future if needed. It also seems like it may play better with APIs like Windows Holographic, but I might just be mis-reading the docs on that one.

The one downside is that it becomes more difficult to adjust depth parameters on the fly, since you'd need to create a new frameOfReference for that. I'm not sure how frequently that need actually arises in the real world, though.

Proposed IDL:
```webidl
dictionary VRFrameOfReferenceInit {
  VRFrameOfReferenceType type = "EyeLevel";
  double depthNear = 0.01;
  double depthFar = 10000.0; // Defaults from existing spec. Worth re-evaluating?
};

interface VRFrameOfReference : VRCoordinateSystem {
  readonly VRFrameOfReferenceType type;
  readonly double depthNear; // Keeping it all on VRFrameOfReference here for simplicity
  readonly double depthFar;
  readonly attribute VRStageBounds? bounds;
};

partial interface VRSession {
  Promise<VRFrameOfReference> createFrameOfReference(VRFrameOfReferenceInit init);
};
```

**Comment by NellWaliczek** [comment]
O_o
I swear I left I comment here on Tuesday...Oooookay....
I totally agree that it's a bit unclear about when the depth data changes are committed... However, it's worth noting that VRSession.getPose() doesn't actually take a VRFrameOfReference; it takes a VRCoordinateSystem.  Also, the depth data doesn't actually have anything to do with the frame of reference or position... it has to do with rendering.
So that said, I *think* the proposal I'm about to put out for render buffers might accidentally address this in a way that we can all get behind, but if that's not the case, let's keep chatting about this one and see if we can find something else that works!

**Comment by toji** [comment]
LOL. You did comment on the related pull request that I posted: https://github.com/w3c/webvr/pull/214

But thanks for re-clarifying here. :)

**Comment by NellWaliczek** [comment]
Hah!  That's what I get for trying to get work done before finishing my morning coffee ^_^

**Comment by toji** [comment]
I think this has mostly rendered moot by the introduction of `VRPresentationFrame`, since it can be made trivially be made clear now that the near and far depth changes only take effect on the next provided frame.
