### ISSUE TITLE
Add Acknowledgements

### ISSUE THREAD

**Issue by cvan** [w3c/webvr#22]
<a href="https://github.com/cvan"><img src="https://avatars.githubusercontent.com/u/203725?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [cvan](https://github.com/cvan)**
_Monday Feb 29, 2016 at 00:32 GMT_
_Originally opened as https://github.com/MozVR/webvr-spec/issues/14_

---

**Comment by toji** [comment]
nothing against having an Acknowledgements section, but nobody seems quite sure what to put in it. :) Removed for now in 84d8d8bcbd6ec661815f30e86acb89b60d4df8ba, feel free to add it back in at any time if you think of something/someone to acknowledge.
