### ISSUE TITLE
Problem with WebVR Enable

### ISSUE THREAD

**Issue by phtester3** [w3c/webvr#220]
I went to vrporn.com a few days ago and ive tested some porn videos, then appeared an message to install WebVR so ive clicked NO,  because i though was a virus, then i could not load videos, then it was a message: type internet://webvr-enable to activate webvr ok i did that and worked fine, then i saw one porn really enjoyed , but today i was feeling i need a second dose then the same problem you need to type webvr enable on my Samsung S6 (wtf i done that yesterday) so i went again and for my surprise and went to a blank page with a few writings interet:/user with some scary comments and i began to feel bad for myself i dont know if watching porn on vr is illegal or something i feel not friendly place

**Comment by toji** [comment]
It sounds as if you're having some trouble with the Samsung Internet browser for GearVR? This repository is for development of the WebVR spec, so we generally can't provide support for specific browsers. I asked around and was pointed to the FAQ portion of [this page](http://developer.samsung.com/internet#faq), which provides ways to get help with the Samsung browser in particular. From that page:

**How can I get customer support for Samsung Internet on Galaxy devices?**

You can send user feedback by selecting `[MORE] -> [Send feedback]` menu in Samsung Internet for Android. Or go to https://help.content.samsung.com/csweb/ticket/createQuestionTicket.do and select 'Internet for Samsung Galaxy'; in the 'Service' field.
