### ISSUE TITLE
Managing multi-GPU systems

### ISSUE THREAD

**Issue by toji** [w3c/webvr#223]
On systems with multiple graphics adapters (SLI/Crossfire or an integrated/discreet pair like many laptops) the underlying graphics context driving the VR hardware must be the one that the headset video output is actually physically connected to. Currently the web has no mechanisms for handling that, which is a problem for WebVR.

This issue and the high level solutions are courtousy of Microsoft. I'm fleshing out the proposal and filing here so they have a bit more bandwidth to work on other high priority items (like VR Input).

## Overview: ##
There's two different categories of app that developers may fall into:

 - **VR Centric:** The app's primary use case is VR, and as such it doesn't mind initializing resources in a VR-centric fashion, which may include asking users to select a headset as soon as the app starts. An example would be a game which is dependent on VR presentation and input.
 - **VR Enhanced:** The app can take advantage of VR, but it's used as a progressive enhancement rather than a core part of the experience. Most users will probably _not_ interact with the app's VR features, and as such asking them to make VR-centric decisions early in the app lifetime would be confusing and innapropriate. An example would be a news site with an embedded 360 photo gallery or video. (We expect the large majority of early WebVR content to fall into this category.)

In the first case, it makes sense to allow developers to indicate at WebGL context creation time what `VRDevice` the context will be used with so that it can be initialized on the correct adapter. The suggestion is that this be passed as an optional `WebGLContextAttributes`, which acts as a hint to the system for which VR device will be using the context in the future. The system should be able to ignore this in cases where it's simply not applicable (Mobile device, only one GPU, etc.)

In the second case, though, initializing the canvas this way may force developers to have their users pick very early on which VR display they intend to use the device with. Going to a news site and having it immediately ask for which headset you intend to use even when there's no obvious VR content on screen is not a desirable user experience. In this case, the canvas can only know which device it's going to be used with at the point that the VR session begins using it.

In this case, it seems reasonable to use the existing WebGL [context loss and restoration](https://www.khronos.org/registry/webgl/specs/latest/1.0/#5.14.13) mechanism. If an exclusive session makes use of a canvas that isn't already on the right adapter the context is lost and (if properly handled) will be recreated with the correct GPU. (This makes an argument for something I proposed in #218, which is to have sessions explicitly bound to a canvas element at creation time. That makes session creation a perfect point for the context check, and the session creation can be rejected if the context isn't compatible or able to be made compatible.)

Context loss is not something that many WebGL apps handle well today, which is unfortunate. The biggest issue is that it's a rare occurance, and as a result can often be ignored semi-safely. Having WebVR force it's use may prod developers and frameworks to be more aware of the context loss issue and handle it accordingly, which would be a positive outcome. On the flip side, unless the developer is using a machine with the right kind of GPU configuration to hit this path (or if they have one but just so happen to hit the right defaults every time) it's going to be pretty easy for them to ignore the issue here too and only find out it's a problem with users with a "problematic" system configuration begin complaining.

Ideally we could come up with some sort of forcing function to actively validate that the page is set up to handle context loss, even if it's not necessary for the developer's current setup. To be honest I have no idea what that would look like, though.

Along with that it would be nice to enable apps to check to see if a given context will be compatible with a given `VRDevice`. This could be handled as part of a expanded approach to the current `supportsSession()` concept. In it, the developer could pass in desired session creation args and get back some indication of how those args would be handled if a session was actually requsted with them, similar to how WebGL accepts a set of desired context creation args and then reports back the actual arguments used to create the context afterward. This could be a useful tool in the future if session creation gains more capabilities.

## Tangential Itermission: ##

An alternative to all of this, which is possibly a bit drastic but worth considering, is to limit WebVR to only expose a single VRDevice at a time. (Multi-HMD systems could have browser settings to allow the user to select which device is the primary.) Then contexts can be forced into VR mode at creation all the time with a simple `vrCompatible` bool, since there's only ever going to be one device that you could possibly initialize with.

This may feel limiting, but in reality would likely work out really well for the vast majority of users. Having more than one HMD for a computer is generally impractical for both cost and power reasons, and future trends that drive cost and power requirements down are more likely to enable higher end all-in-one and mobile-based devices than focus on multi-HMD desktops. In almost all cases it's easier (and safter?) to have shared VR experiences via networked devices than a physical connection to the same machine.

One possible near term exception to this is devices like [Asus' Tango-enabled ZenPhone](https://www.asus.com/us/Phone/ZenFone-AR-ZS571KL/) which can use Tango tracking or Daydream, but not at the same time due to power constraints. Both of those modes could viably be exposed as VRDevices. Alternately, though, they could also be feasibly exposed as different session types of a single device. (Non-exclusive can use Tango tracking, while exclusive mode switched to Daydream or something like that.)

I'm genuinely curious how much appetite there is for a single-device approach, but I'm going to stick to discussing the more general approach below.

## Rough IDL: ##
```webidl
//
// WebGL
//

partial dictionary WebGLContextAttributes {
    VRDevice compatibleVrDevice = null;
};

//
// VR Device
//

partial interface VRDevice : EventTarget {
  Promise<VRSessionCreateParameters> supportsSession(VRSessionCreateParametersInit parameters);
  Promise<VRSession> requestSession(VRSessionCreateParametersInit parameters);
};

//
// VR Session
//

typedef (HTMLCanvasElement or
         OffscreenCanvas) VRCanvasSource;

dictionary VRSessionCreateParametersInit {
  VRCanvasSource canvas;
  boolean exclusive = true;
};

interface VRSessionCreateParameters {
  readonly VRCanvasSource canvas;
  readonly boolean canvasWasCompatible;
  readonly boolean exclusive;
};

```

## Example Usage: ##
```js
// On page init (for VR-centric apps)
let gl = canvas.getContext("webgl2", { compatibleVrDevice: vrDevice });
LoadGLResources();

// Context loss handling (for VR-enhanced apps)
canvas.addEventListener("webglcontextlost", event => {
  // Inform WebGL that we handle context restoration
  event.preventDefault();
  // Handle any cleanup you may need
}, false);

canvas.addEventListener("webglcontextrestored", LoadGLResources, false);

function CheckForCompatibleCanvas(canvas) {
  return vrDevice.supportsSession({ canvas: canvas, exclusive: true })
      .then(result => {
        return result.canvasWasCompatible;
      });
}

function BeginVRSession() {
  vrDevice.requestSession({ canvas: canvas, exclusive: true }).then(session => {
    // Shouldn't resolve until the canvas in on the right adapter.
    // Now VR as ususal!
  }).catch(err => {
    // Possibly got here because the canvas wasn't on the right adapter and you
    // failed to handle context loss correctly?
  });
}
```

## Outstanding Questions: ##
 - How do we ensure that developers don't gloss over context loss handling when it "works on their machine"?
 - Are the various browser able to properly handle the possibility of having a single canvas run on a different adapter from the rest of the page?
 - Do we possibly want to commit to a single device world? Would have several other ripple effects.

**Comment by RafaelCintron** [comment]
Thank you for putting this together, Brandon!

**Re: Ensuring developers don't gloss over context loss handling**: WebGL already has a context lost extension web developers can use to test their content. So they will not have to procure hardware for testing. As for handling it in the first place, I don't have a better answer besides continued evangelization. With increasing prevalence of hybrid laptops, there will be more incentive for web developers to make this work moving forward.

**Re: Content on the same page run on different adapters**: Our initial implementation of multi-GPU would be to migrate all of the web content onto the VR GPU. Otherwise, managing multi-adapter img, video, svg-as-image and future DOM-to-texture features will pose a challenge, and possibly make things poorer performing.  

**Re: Single device world**.  Given what I wrote above, I'm not a big fan of limiting VRDevices using the browser UI. If the user picks the power hungry GPU as their "VR device", then that results in poor battery life for non-VR pages. To avoid this, we'll just end up back to trying to guess the best adapter, which is not a good place to be.

**Comment by NellWaliczek** [comment]
Hey Brandon, thanks so much for kicking off this conversation!  

I agree it's a thorny issue to encourage "best practice" behavior when the required test matrix can be so large.  Our hope is to design an API that encourages this "good behavior" by its very structure rather than leaving it up to luck (and random machine configurations).  One way to do this, is to require the developers to always set the `VRDevice` on the context either at creation time or later.  For the former it would be via the `WebGLContextAttribute` and the latter could be via a dedicated API for this purpose.  The key is that setting the `VRDevice` on a context must be explicitly done, rather than implicitly done, to encourage the correct behavior.  Of course developers could choose to not add `webglcontextlost` handlers, but that would be less likely to happen if they were forced to designate the `VRDevice` under all circumstances.

One other thing to consider is that context loss should not be required before the session has been successfully established.  For example, in response to `requestPresent()`, the Edge implementation asks for domain approval (similar to fullscreen) before taking over the `VRDevice`.  Since this is something the user could reject, it would be bad if we fired `webglcontextlost` too soon.

What about the following variation on your proposal?  One other variation could be to move the `ensureVRCompatibility()` function to the `VRDevice`.  No strong opinion here; we just put the related properties together on the webgl context as a starting point.

```JS
//
// WebGL
//
partial dictionary WebGLContextAttributes {
    VRDevice compatibleVrDevice = null;
};

partial interface WebGLRenderingContextBase {
  Promise ensureVRCompatibility(VRDevice);
};
```
Here's how it would be used in the VR centric flow
```JS
// On page init for VR-centric pages
let gl = glCanvas.getContext("webgl", { compatibleVrDevice: vrDevice });
LoadGLResources();

vrDevice.requestSession({exclusive: true}).then(session => {
  onSessionCreated(session);
}).catch(err => {
  // Error cases here
});

function onSessionCreated(session) {
  // Since compatibleVRDevice was passed into context creation,
  // layer construction will succeed
  vrSession.baseLayer = new VRWebGLLayer(vrSession, glCanvas);
};
```
Here's how it would be used in the VR enhanced flow
```JS
// On page init for VR-enhanced pages
let glContext = glCanvas.getContext("webgl");
LoadGLResources();

// Context loss handling (for VR-enhanced apps)
glCanvas.addEventListener("webglcontextlost", event => {
  // Inform WebGL that we handle context restoration
  event.preventDefault();
  // Handle any cleanup you may need
}, false);

glCanvas.addEventListener("webglcontextrestored", LoadGLResources, false);

vrDevice.requestSession({exclusive: true}).then(session => {
  onSessionCreated(session);
}).catch(err => {
  // Error cases here
});

function onSessionCreated(session) {  
  // Since compatibleVRDevice was not passed into context creation, ensureVRCompatibility() 
  // must called (even if the adapter is correct) or layer construction will throw an exception.
  
  // When ensureVRCompatibility() is called:
  //   If the adapter is already correct, the promise will fulfill immediately without causing
  //   any context loss.
  //
  //   If the adapter is mismatched, contextLost will be fired.  If preventDefault() is called
  //   in response, then contextRestored will be fired.  Once contextRestored is finished, the 
  //   promise will fulfill. If preventDefault() is not called, the promise will reject.
  ensureVRCompability(vrDevice).then({
    vrSession.baseLayer = new VRWebGLLayer(vrSession, glCanvas);
  });
};
```

**Comment by toji** [comment]
As we discussed on the implementors call, this direction sounds pretty good. I'll put together a pull request for it.

**Comment by toji** [comment]
Related pull request has been merged, closing this issue.

**Comment by wrr** [comment]
I'm sorry for posting in a closed issue, but just discovered the context-loss handling requirement.

On mobile devices a web page (or the whole browser) tends to be killed if it uses too much memory. One technique  to alleviate this issue is to remove all resources from JS memory after the resources are  passed to WebGL. This approach makes it impossible to handle context loss, but it seems that today context loss is far less frequent than WebGL page dying on mobile due to RAM limits.

Maybe WebVR could expose a flag that says if VR switch would possibly cause context loss? If I understand correctly, single GPU mobile devices will never require the context loss during VR switch so  an application could continue to remove resources from JS memory after passing them to WebGL.

**Comment by toji** [comment]
I'm not sure I follow the concern. It's true that mobile devices are far more likely to nuke a page or the whole app than to try and lose a single context, but memory use is not really the concern here.

On multi-GPU systems we'll semi-frequently need to switch the WebGL context over the a different GPU than it was originally created on in order to communicate efficiently with the VR device. The only real mechanism we have for doing that is context loss (we can't silently move contexts between GPUs in all cases without data loss.) It's annoying, yes, but that's why we allow the context creation attribute, which will avoid the context loss in the cases where it's appropriate.

As you pointed out this is largely not a problem on mobile, which is exactly why we need the context loss handling requirement. It's very possible that a developer would do all of their development on a mobile device and therefore never trigger a context loss. They may release their app thinking "It's working fine!" and then be surprised to get a stream of support requests from users with beefy desktop SLI rigs that, by all rights, should run the content much better than the mobile device but are triggering a context loss to move onto the right GPU. By forcing that context loss handling is present in all cases, even when we don't expect it to happen, we ensure the developer has to consider it to some degree. (They could absolutely just stub in an empty event handler and move on with their life, but at that point any failures are on them for ignoring the errors we raised.)

**Comment by wrr** [comment]
My concern is that, as your wrote, majority of 'VR Enhanced' pages users won't be using VR. To handle context loss the application needs to keep all the resources in JS memory, so increase memory usage for all users, including the majority that will never enter the VR mode.

If it would be possible for WebVR to expose a flag that says that a given system has multi-GPU and the user has some WebVR hardware that can possibly trigger context loss, then the app could be keeping these resources in memory only on such systems, and on others it could still release the resources to reduce RAM usage.

**Comment by toji** [comment]
Certainly there's an argument to be made that it's more efficient to reload a scene if all the source resources are in memory, but I actually can't imagine that's a terribly practical route for most pages. In a great many cases you probably just want to re-fetch the resources like you did during the initial load and trust that the browser cache will prevent repeated downloads. In the case of something where the resources can't be re-downloaded (user generated content, dynamic content) you're either already saving the content as you go so the user can load/share/etc it later OR the content is intentionally ephemeral and would never really survive a context loss regardless. You do have an advantage with WebVR over normal context loss, at least, in that you'll know when you're about to take an action that could trigger the loss.

In any case, we know that context loss handling sucks. Sorry. It's a reality that we have to deal with on some systems, though, and the nature of the web means that it's usually better to treat everything as if it could be worse case scenario even on platforms where it's probably not the case.

**Comment by wrr** [comment]
If re-fetching the resources is a recommended practice for handling context loss than indeed this doesn't require any extra memory, so addresses my concerns about increased memory usage.

I wonder if it would be feasible for browsers to implement a simple context loss handling for VR: if an application doesn't register context loss handler and the user enters VR, just reload the page but this time use a VR-enabled GPU. Many VR experiences do not have any important state to be preserved during  context loss handling and application level re-fetching of resources can require significant complexity. Without re-fetching application can implement simple one-way state transitions [loading phase] => [initialization phase] => [presentation/interaction phase] re-fetching adds tricky to handle cycles to these transitions
