### ISSUE TITLE
Location/behavior of getViewport

### ISSUE THREAD

**Issue by toji** [w3c/webvr#231]
After #218, the viewports for a layer are queried from the `VRPresentationFrame` like so:

`let viewport = vrFrame.getViewport(vrSession.baseLayer, view);`
  
With a variant for multiview, which is view-agnostic:

`let viewport = vrFrame.getViewport(vrSession.baseLayer);`

While I've expressed in the past that I feel viewport retrieval feels most natural on the `VRLayer` type it's associated with Microsoft is concerned that such an arrangement doesn't properly imply that the viewports may change frame-to-frame. I still think the current method could be cleaned up a bit, however. Specifically, given that the viewports are unique to a view and layer, it seems like one of those objects should be the source that the viewport is queried from instead of a third object (frame). Given that the views are frame-specific, querying viewports from them feels like it should alleviate Microsoft's concerns about implying the viewport lifetime.

In the multiview case, I don't see the harm in having all views return the same viewport for the sake of keeping the interface simpler and more consistent.

Additionally, while I argued against it a bit previously, if we're not going to associate the viewport with a specific layer type we should just declare a single layer-agnostic viewport type and be done with it. Chances are _pretty_ good that `x, y, width, height` will cover most situations in which a viewport is necessary. If we end up in a situation where that's not sufficient it's also likely that this will be the least of our worries.

So, the proposed changes are:  

```webidl
// IDL
interface VRViewport {
  readonly attribute int x;
  readonly attribute int y;
  readonly attribute int width;
  readonly attribute int height;
};

interface VRView {
  readonly attribute VREye? eye;
  readonly attribute Float32Array projectionMatrix;
  VRViewport getViewport(VRWebGLLayer layer);
};
```

```js
// JS
function onDrawVRFrame(vrFrame) {
    let pose = vrFrame.getDevicePose(vrFrameOfRef);
    gl.bindFramebuffer(vrSession.baseLayer.framebuffer);
    
    if (vrSession.baseLayer.multiview) {
      let viewport = vrFrame.views[0].getViewport(vrSession.baseLayer);
      gl.viewport(viewport.x, viewport.y, viewport.width, viewport.height);
      drawMultiviewScene(vrFrame.views, pose);
    } else {
      for (let view in vrFrame.views) {
        let viewport = view.getViewport(vrSession.baseLayer);
        gl.viewport(viewport.x, viewport.y, viewport.width, viewport.height);
        drawScene(view, pose);
      }
    }

    // Request the next VR callback
    vrSession.requestVRPresentationFrame().then(onDrawVRFrame);
}
```

**Comment by NellWaliczek** [comment]
Oooh, this looks good!  

One possible variant could be:
```js
interface VRView {
  readonly attribute VREye? eye;
  readonly attribute Float32Array projectionMatrix;
  VRViewport? getViewport(VRLayer layer);
};
```
When passed a VRWebGLLayer it would be guaranteed to return an object, but for other future layer types (like the often discussed VRVideoLayer) maybe not? What do you think?

Alternatively, I wonder if there's an existing interface we could use instead having a custom VRViewport.  @travisleithead, thoughts?

**Comment by toji** [comment]
I was going to propose that anyway, but decided to try rocking the boat less first. 😁 I'm good with it!
