### ISSUE TITLE
Do not treat activate events as a user gesture

### ISSUE THREAD

**Issue by ddorwin** [w3c/webvr#248]
The explainer currently says, "The activate event acts as a user gesture..." The intent is that WebVR presentation can start from the event handler without requiring a user gesture, such as a click.

WebVR should not generate a generic user gesture state/bypass because this would affect all other specs and implementations that use a user gesture for privacy and/or security mitigation.

Instead, WebVR should differentiate user gestures and other cases that allow the user gesture requirement to be bypassed. In the spec, it may be helpful to have internal state/variables and/or algorithms related to "Is presentation allowed?"

**Comment by ddorwin** [comment]
This was about the 2.0 explainer, but we may want to clean up the 1.1 text as well.

**Comment by cvan** [comment]
this is touched on in PR #256. @toji: do you want to assign this to yourself and/or close?

**Comment by toji** [comment]
Yeah, I'm going to consider this closed by #256.
