### ISSUE TITLE
sittingToStandingTransform may be a misnomer?

### ISSUE THREAD

**Issue by cvan** [w3c/webvr#26]
<a href="https://github.com/toji"><img src="https://avatars.githubusercontent.com/u/805273?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [toji](https://github.com/toji)**
_Wednesday Mar 02, 2016 at 21:45 GMT_
_Originally opened as https://github.com/MozVR/webvr-spec/issues/18_

---

A bit of feedback I've received is that the concepts of "sitting space" and "standing space" that we've borrowed from OpenVR may not be accurate representations of the values we're providing. For example: It's definitely possible to stand in place while using an Oculus Rift, and you probably want to when using controllers like Touch. Since there's no sense of where you are in relation to the room, this would still be reported in "sitting space", though. Similarly, you may want to sit down with a Vive but still have the scene oriented to your room using "standing space." The actual values reported right now in either case should be fine, but the verbiage is weird.

I propose that we run with the verbiage of "stage" that we've already defined. So `sittingToStandingTransform` becomes `stageTransform`. We'd also have to come up with a term for the default space ("relative" comes to mind but may be too vague) and change some verbiage in the spec, but otherwise everything continues to work the way it does now.

Or we could just decide that this is a silly thing to worry about and move on. :)

**Comment by cvan** [comment]
<a href="https://github.com/Sneagan"><img src="https://avatars.githubusercontent.com/u/1883491?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Sneagan](https://github.com/Sneagan)**
_Thursday Mar 03, 2016 at 21:15 GMT_

----

I agree completely with the point and do like `stageTransform` as an alternative. `relative` *is* a little vague, but I have to admit that I like the consistency of the `relative`/`fixed`/`absolute` from other web standards areas that's implied. Which space were you thinking of as the default?

**Comment by cvan** [comment]
<a href="https://github.com/toji"><img src="https://avatars.githubusercontent.com/u/805273?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [toji](https://github.com/toji)**
_Thursday Mar 03, 2016 at 21:23 GMT_

----

sitting/relative/start-point-local has to be the default space, because it's the only common space between all the systems we want to support. Works for everything from Cardboard to Vive.

**Comment by cvan** [comment]
<a href="https://github.com/Sneagan"><img src="https://avatars.githubusercontent.com/u/1883491?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Sneagan](https://github.com/Sneagan)**
_Thursday Mar 03, 2016 at 21:52 GMT_

----

Awesome, that's what I was hoping. That said, though, `relative` might be a bit confusing. Relative to what? `local` seems pretty descriptive. What do you think of these:

- Stage as `local` when space traversal will happen primarily through controller input.
- Stage as `global` when the VR space is traversable by one-to-one human motion.

Reading these I realize I may be conflating sitting and standing with fixed position and room scale VR unnecessarily, but that feels like the real distinction we're making.

**Comment by cvan** [comment]
<a href="https://github.com/toji"><img src="https://avatars.githubusercontent.com/u/805273?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [toji](https://github.com/toji)**
_Thursday Mar 03, 2016 at 22:10 GMT_

----

I don't have a problem with the `local` verbiage. `global` feels awkward to me in the context that we're talking about. If you asked me what that meant without prior knowledge I'd hazard a guess that position is reported in Lat/Lon. ;D We're really talking about movement being relative to either a "soft" origin defined by either the users starting pose or the last call to `resetPose` or a "hard" origin that's configured specifically for their physical space.

That's why I like the term "stage", because it's a pretty good analogy (I feel) for the configured play space. A theatre stage is a confined space that the actors have to move in, but through clever scenery changes and theatrical tricks can feel as though it represents a much larger world than the actual floor space suggests. Describes the room-scale VR experience pretty well!

**Comment by cvan** [comment]
<a href="https://github.com/Sneagan"><img src="https://avatars.githubusercontent.com/u/1883491?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Sneagan](https://github.com/Sneagan)**
_Thursday Mar 03, 2016 at 22:27 GMT_

----

Ah that's clearer. I'm completely behind `stage` and see what you mean about `global` (been spending a ton of time in spherical and geographical coordinate systems recently). What do you think of `world`. World space obviously has other connotations in game environments, but it might still work in this context.

**Comment by toji** [comment]
This is being addressed by https://github.com/w3c/webvr/pull/149
