### ISSUE TITLE
exclusive by default boolean API design

### ISSUE THREAD

**Issue by domenic** [w3c/webvr#262]
https://github.com/w3c/webvr/blob/d44a37a24781bf360a4fed8a99fee9f8caf9e176/explainer.md states

> Exclusive Access: The default mode, but can be explicitly requested with the exclusive: true dictionary argument.

This goes against the TAG [API Design Principles](https://w3ctag.github.io/design-principles/#prefer-dict-to-bool) and [Web IDL](https://heycam.github.io/webidl/#dfn-dictionary-member-default-value) which warn that the default for boolean options should always be false, to conform to normal JavaScript practices.

Consider flipping the adjective so that the default is false. (`inclusive: true`?)

**Comment by domenic** [comment]
Reviewing the IDL, this problem is EXTENSIVE in VRWebGLLayerInit.

**Comment by toji** [comment]
I'll review the `exclusive` recommendation with the rest of the group, but for the `VRWebGLLayerInit` we're explicitly mimicking the [`WebGLContextAttributes`](https://www.khronos.org/registry/webgl/specs/latest/1.0/#WEBGLCONTEXTATTRIBUTES) dictionary.
