### ISSUE TITLE
setCompatibleVrDevice is mis-cased

### ISSUE THREAD

**Issue by domenic** [w3c/webvr#263]
Per https://w3ctag.github.io/design-principles/#casing-rules it should be "VR", not "Vr".

Similarly the dictionary option `compatibleVrDevice`.

This is especially amusing given how it is used on a class that does the casing correctly for two-letter acronyms (the "GL" in WebGLRenderingContextBase).

**Comment by toji** [comment]
Thanks for pointing this out, and especially for the reference to the casing rules!
