### ISSUE TITLE
vrSession.endSession() is needlessly verbose

### ISSUE THREAD

**Issue by domenic** [w3c/webvr#265]
Should just be vrSession.end()

**Comment by toji** [comment]
Good catch, thanks! But does this cause a conflict with the recommendation in #266? Even it it's allowed it feels strange to have both an event and function named "end". Any precedent for that elsewhere in the platform?

**Comment by domenic** [comment]
I think it's pretty common actually. E.g. the play event and the play() function on media elements, or the click event and the click() function on HTML elements.

**Comment by toji** [comment]
Well then, problem solved as far as I'm concerned. :)
