### ISSUE TITLE
'ended' event is using the wrong tense

### ISSUE THREAD

**Issue by domenic** [w3c/webvr#266]
Event names use present tense (cf. "focus", "blur", not "focused", "blurred") and so it should be "end" instead.

**Comment by toji** [comment]
Thanks for pointing this out.

**Comment by domenic** [comment]
FYI, I just filed https://github.com/whatwg/html/issues/2891 as I noticed there are a few exceptions on the platform, just surveying HTML. I am 95% sure they are for legacy reasons though. (The bug is filed to confirm that and document it if so.)
