### ISSUE TITLE
Explainer nits

### ISSUE THREAD

**Issue by domenic** [w3c/webvr#267]
- Functions, for some reason, begin with an uppercase letter (e.g. `OnVRAvailable`, `BeginVRSession`), which looks alien to JavaScript developers. (This is also not consistent; by the time we get to "main render loop" it seems to switch back to normal initial-lowercase casing for a few functions.)
- `OnVRAvailable` is declared as an `async` function, but does not use `await`. Either use `await` in place of the manual promise-handling, or remove the `async` qualifier.
- Similarly, `OnSessionStarted` uses `await`, but is not declared as an `async` function. However, it also uses manual promise-handling. Pick one and stick with it?
- Another instance: the "Room-scale tracking and boundaries" example uses a non-async arrow function in the `catch` handler, but then uses `await` inside of it.
- The method `VRDisplay.requestSession` does not exist (there is no static method with that name). Probably it should be `VRDisplay.prototype.requestSession` or `vrDisplay.requestSession`, or perhaps `VRDisplay`'s `requestSession()`. Similarly `VRSession.baseLayer`, `WebGLRenderingContextBase.setCompatibleVrDevice`, `VRSession.requestFrame`, `VRWebGLLayer.framebuffer`, `VRSession.endSession`, `HTMLCanvasElement.getContext`... I stopped keeping track.
- "Beginning a VR session" sometimes says `VRDisplay` and sometimes `VRDevice`.
-  `[VRPresentationFrame]` has extra brackets around it. Maybe it was supposed to be a link.

**Comment by toji** [comment]
Okay, think I've addressed all of these. Thanks for pointing out the inconsistencies!
