### ISSUE TITLE
Minor explainer IDL issues

### ISSUE THREAD

**Issue by domenic** [w3c/webvr#269]
- `VRSessionCreateParametersInit` has a null default value for `outputContext`, but the value is not nullable (i.e. it's not `VRPresentationContext?`). Probably instead you just want there to be no default value. (That doesn't make it required, it just means that by default it's not present, instead of by default it's null.)
- `framebufferWidth` / height should probably be unsigned long, not long? Although it's just a return type, so it doesn't matter much.
- Consider using [EnforceRange] for framebufferScaleFactor

**Comment by toji** [comment]
All sounds good to me!
