### ISSUE TITLE
Minor potential tweaks to createParameters design

### ISSUE THREAD

**Issue by domenic** [w3c/webvr#270]
The name "parameters" is unusual for this sort of thing in the web world. Perhaps it should be `createOptions` or `creationOptions`?

Alternately, why not just expose these options directly? Creating a whole separate interface (with no constructor, grr) just so that people have to go through `vrSession.createParameters.x` instead of `vrSession.x` (or `vrSession.creationX`) doesn't make sense to me.

Apologies if I'm missing something and these have been discussed before; I couldn't find anything in the explainer.

**Comment by toji** [comment]
Naming option makes sense to me. I don't recall a specific reason for having the intermediate object either, other than the fact that it roughly echoed a previous iteration of the design. I'll bring it up with the group to see if I missed anything.

To be clear, your concern is _not_ the use of an options dictionary in `requestSession` but the use of the `createParameters` attribute on the `VRSession` object, right?

**Comment by domenic** [comment]
Exactly. The options dictionary for requestSession() seems very solid; I'm just thinking there might be minor tweaks to make the reflection of those options back onto the VRSession better.
