### ISSUE TITLE
Meeting at W3C TPAC in November

### ISSUE THREAD

**Issue by DrX3D** [w3c/webvr#280]
I sent this last week to the mailing list, but received no responses. I am hoping there is more here.

The Declarative WebVR Community group wants to hold a meeting at the W3C TPAC this 6-10 November. It would be best if there was not a conflict with the WebVR Group. There are two tentative dates listed for WebVR - Thursday and Friday. I think it would be best to hold these two meetings on the same day, but at non-overlapping times. Has anyone made any official plans for this? Absent any other information, I would prefer Thursday.

**Comment by anssiko** [comment]
Declarative VR Community Group had its meeting at TPAC. For the meeting notes and presentations, see: https://lists.w3.org/Archives/Public/public-decwebvr/2017Nov/0002.html

Related: WebVR Community Group TPAC meeting minutes at #296.
