### ISSUE TITLE
WebVR Empty Black Screen On Google Chrome

### ISSUE THREAD

**Issue by AbhishekKumarTank** [w3c/webvr#281]
When I am trying to run my threejs site on Android Google Chrome v59, with Origin Trial Token, I am getting a black screen. The site comes up for a second and then the screen turns black.

The same site works fine on Samsung Internet Browser for Samsung Gear VR. 

![4095d6a2-25f2-11e7-98d8-59468f9c3186](https://user-images.githubusercontent.com/26770838/29390404-f49b4c86-82a4-11e7-9f16-eeccc03b79ac.png)

I tried this on Pixel, Samsung S7 Edge.
Three js : r86
Operating System: Android 7.1.2, Android 6.0.1
Browser: Chrome for Android 59 with Origin Trial Token
VR Device: Pixel XL, Samsung S7 Edge

**Comment by cvan** [comment]
@AbhishekKumarTank, thanks for trying out WebVR. Have you filed a bug against the [Chromium bug tracker](https://crbug.com/) or [three.js](https://github.com/mrdoob/three.js/issues)?

This repository doesn't track the implementations of WebVR, only the specification. Apologies if that's a bit confusing.

Let me know if you need further help. Thanks!
