### ISSUE TITLE
Feature Request: Emulated standing space

### ISSUE THREAD

**Issue by toji** [w3c/webvr#282]
Throw this one into the "probably a 2.1 feature" bucket.

It would be a huge developer convenience to enable emulated "stage" frame of references where where, if an actual calibrated room layout is not available the developer could specify a fallback height to be used, at which point the data returned would effectively be an "eyeLevel" frame of ref with the origin offset on the Y axis by the requested height.

This would allow developers to use the API-provided matrices directly in more cases, simplifying code significantly. It also encourage apps to gracefully fall back and support a wider variety of devices rather than just throw up an error message if standing space isn't available.

**Comment by kearwood** [comment]
This may provide a lot of benefit through enabling users to configure their own height and having it consistent across sites.

**Comment by toji** [comment]
This was brought up on the most recent implementer call and was well received as a potential quality of life improvement for developers in 2.0. I'll draw up a pull request with a more formal proposal ASAP.

**Comment by toji** [comment]
This is now in the explainer.
