### ISSUE TITLE
Chromium Crashes + Vive on entering VR @ threejs vive examples

### ISSUE THREAD

**Issue by StudioDeTelevision** [w3c/webvr#287]
Hello , using chromium on windows 10 and HTC vive , got webgl crashes on Entering VR  (on button click) with threejs
does anyone have (had) the same behaviour ?

things like that are thrown : ERROR:process_info.cc(608)] range at 0xb0b9321800000000, size 0x21c fully unreadable

**Comment by cvan** [comment]
@StudioDeTelevision, thanks for testing out WebVR 👍

For the Chromium browser-specific implementation, I'd suggest filing an issue here: https://github.com/toji/chrome-webvr-issues/issues

Do you think toji/chrome-webvr-issues#158 is the same issue? If not, feel free to [file a new one](https://github.com/toji/chrome-webvr-issues/issues/new).
