### ISSUE TITLE
issues/feature request - audio

### ISSUE THREAD

**Issue by tiagomoraismorgado88** [w3c/webvr#291]
**from my point of sight, it would be interesting for you to:**

- *including supercollider.js in your framework; (https://github.com/stagas/node-supercollider and https://github.com/crucialfelix/supercolliderjs)*
- *porting libpd to javascript (perharps using emscripten https://github.com/libpd/libpd)*
- *porting csound to webvr (perhaprs using emscripten as well https://github.com/csound/csound)*
- *porting PWGL to WebVR (http://www2.siba.fi/PWGL/)*

---

**furthermore:**

- *using an implementation of fft in opencl (i have forked some in case you may want to take a look https://github.com/tiagomoraismorgado88/Max-gpu.fft);*
- *use that to make an implementation of higher order ambisonics/emulating wave field synthesis in stereo; (possibly based on https://github.com/GameOfLife/WFSCollider)*

**Comment by jsantell** [comment]
[Songbird](https://github.com/google/songbird) and [Omnitone](https://github.com/googlechrome/omnitone) handle this with web audio

**Comment by cwilso** [comment]
Yep.  And doing 3D audio is fairly straightforward in web audio with HRTF-mode PannerNodes.

**Comment by tiagomoraismorgado88** [comment]
**Two things shall be considered in first place:**
- *supercollider, puredata, csound and pwgl, are state of the art opensource environments for sound synthesis, algorhtmic composition, etc.*
- *that means they are not ambisonics implementations*

---

**by trying to replicate wave field synthesis in stereo and implementing it throughout webcl, for instance:**
- *you would be able to do things that you are not capable of doing with standard ambisonics, as wfs is an higer order implementation of ambisonics, so more interpolation, etc. and having a framework for wave field synthesis, would allow you to do: vr with real large scale speaker arrays*
- *i think trying at least to learn about wave field wouldn't be a bad idea: https://en.wikipedia.org/wiki/Wave_field_synthesis*

---

**bearing this in mind:**
- *i think you would benefict extensively of such a thing*

---

**so, my question is**
- *why not considering wave field syntheis for vr both in stereo emulaton, and as a possibility for doing large scale speakers clusters arrays?*

---

---

**well, I have nothing against google, they make really outstanding stuff:**
- *chrome browser for instance, has a pretty solid architecture, and is one of the state of art browsers available these days.*
- *i would specially regard this as it is opensource, so you can touch the code and making modifications to it.*

---

**from my perspective, working with pwgl, csound, libpd and supercollider, within the context of vr may, within thyself, may be benefitial, as:**
- *these are state of the arts environments for things like sound synthesis and so on so forth.*

---

**and better:**
- *most of them are available with ports for openframeworks, which supports out of the box emscripten compilation, so it shouldn't be that difficult difficult to bind those to javascript.*

---

**in fact: supercollider:**
- *has clients for both node, and a language side implementation for javascript (i've included links). bearing this in mind,*

---

*i think it could, within thyself, be a good option to at least consider:*
- *some form of binding these kinds of things to webvr.*
- *you guys  and everyone in the community could benefict of it into a larger extent, so, why not?*

**Comment by cwilso** [comment]
I'm not sure what you're looking for, but it sounds like you'd be more interested in the Web Audio Working Group (https://www.w3.org/2011/audio/).  I know most of us there are familiar with at least CSound and SuperCollider.  Baking them into browsers seems very unlikely, but with forthcoming work on AudioWorklets, at least it should be possible to compile them into the web (possibly in WebAssembly, even), and connect them directly to audio outputs.

My understanding of wavefield synthesis is that it wouldn't work in stereo - it needs many transducers to invoke the wave fields, or the spatial aliasing makes it ineffective.  If you just want to position synthesized or sampled sound sources in a 3D sound field, the HRTF panner in Web Audio is quite effective, and designed (obviously) for stereo headphones.  If you want Ambisonics panning of streamed sources, Hongchan's work on OmniTone has proven that's quite doable on top of Web Audio too.

I would strongly advise against baking in a given sound library (other than Web Audio, which is already built into the browser implementations), and focus on the interactions - like, do we need a sound panner node that is hooked up in audio rate to a camera direction, for better tracking in a headset.

**Comment by tiagomoraismorgado88** [comment]
**well, from my point of sight:**
- *it's possible to run supercollider at least in a web browser (as i mentioned you have clients for both javascript and node available)*
- *it's possible as well to run pure data and csound in a browser, as they are c/c++ based, and you can compile them with emscripten*

---

**regarding  wfs:**
- *you have several environments for wfs sound spatialization such as wfscollider writen by miguel negrão, which allow you to basically apply wave field synthesis to a massive loudspeaker array, but also to stereo headsets, allowing you to emulate the wfs phenomena in stereo (it's never the same thing, but it could be enhanced)*

**Comment by toji** [comment]
I certainly don't want to discourage anyone from pursuing novel approaches to various VR-related problems. However, this repo is for development of the WebVR spec itself, while this issue appears to deal primarily with audio libraries? It's not clear to me if changes to the WebVR spec (or any other spec) are being proposed here, and if the desired effects can be achieved without spec changes it's probably best to either create a new repo to implement a library in or move the discussion to the repo of an existing library with similar goals.

Closing this issue to ensure our issues list stays a bit more focused, but if I've missed something and there is indeed a spec change being proposed please let me know!
