### ISSUE TITLE
Agenda for W3C TPAC 2017?

### ISSUE THREAD

**Issue by NellWaliczek** [w3c/webvr#296]
Hey folks! @toji and I were chatting today and we're both hearing that there may be some interest in meeting at [TPAC ](https://www.w3.org/2017/11/TPAC/Overview.html) this week after all.  The WICG folks have graciously offered us their 10:30-12:30pm timeslot on Thursday so, if there is indeed interest, we're thinking of accepting.  Some possible topics are:
- [RAF loop syntax](https://github.com/w3ctag/design-reviews/issues/141#issuecomment-339559167)
- [TAG Feedback about performance isolation](https://github.com/w3c/webvr/issues/292)
- [Deferred sessions and navigation](https://github.com/w3c/webvr/pull/256/files)
- [Test api design](https://github.com/w3c/webvr/issues/187)
- Call for suggestions for features to add to the roadmap

Does this sound like something folks would be interested in joining?  I think either way, @toji and I will probably camp out in the room (Sandpebble E) during this time and see if we can set up a call for remote folks who want to join in.

**Comment by cwilso** [comment]
If you want to slide the timing a bit earlier (to whenever @toji gets in), the room's currently open, just let me know.

**Comment by darktears** [comment]
I'll be joining remotely.

**Comment by NellWaliczek** [comment]
Thanks @cwilso! Do you know what we need to do to set up a call-in?

**Comment by cwilso** [comment]
Use a phone or laptop/hangout.  The W3C doesn't have a supply of polycoms.

**Comment by NellWaliczek** [comment]
We're using this hangout

**Comment by toji** [comment]
Hangout link for external participants: https://hangouts.google.com/hangouts/_/google.com/webvr

**Comment by dontcallmedom** [comment]
irc.w3.org #webvr channel for reading the notes as they're being taken

**Comment by anssiko** [comment]
WebVR CG meeting minutes:
https://www.w3.org/2017/11/09-webvr-minutes.html
