### ISSUE TITLE
Dec 1st F2F Agenda

### ISSUE THREAD

**Issue by toji** [w3c/webvr#305]
Rough Agenda for Immersive Web CG meeting on 12/1
Hangouts call: https://hangouts.google.com/hangouts/_/google.com/webvr

(All times in PST)

11:00 - CG/API name discussion
11:30 - AR potential breaking changes
- Device selection
- Sensor permissions
- Hand-held vs. face-worn vs. other
- See-thru vs. pass-thru (rendering changes)

12:00 - Lunch

1:00 - AR potential breaking changes pt 2 (if needed)
1:30 - Communication plan to developer and ecosystem
2:00 - What repos need opening? Examples may include:
- WebVR 2.0
- AR-focused feature work
- Video layer?
- Webvr.info
- samples
- WebVR Rocks
- Gltf favicons
- 3D object viewing tag; start as a library to evaluate?

3:00 - Review state of input

**Comment by toji** [comment]
Thanks all who attended this meeting! I feel like it was highly productive!

**Comment by cvan** [comment]
@toji thanks for taking this on. wish I could've come earlier, but I really enjoyed the productive chat and enthusiasm of the parts I did catch 👍 

for next steps (e.g., creating GitHub orgs and creating/transferring repos), how should we proceed? W3C CG mailing list, GitHub issues, ideas?
