### ISSUE TITLE
Spec Gamepad property changes

### ISSUE THREAD

**Issue by cvan** [w3c/webvr#39]
<a href="https://github.com/cvan"><img src="https://avatars.githubusercontent.com/u/203725?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [cvan](https://github.com/cvan)**
_Tuesday Apr 12, 2016 at 00:46 GMT_
_Originally opened as https://github.com/MozVR/webvr-spec/issues/31_

----

In @toji's latest Chromium builds (see [patch diff](https://chromium.googlesource.com/experimental/chromium/src/+/refs/wip/bajones/webvr_1%5E%21/)), there's a property `pose` now exposed on the `Gamepad` objects. (See [example of usage](https://github.com/toji/webvr-samples/blob/c8a4392/XX-vr-controllers.html#L232-L276).)

We should document the [WebIDL changes in the WebVR spec here](https://w3c.github.io/gamepad/#gamepadevent-interface).

We ought to also file an issue against [the Gamepad API spec](https://github.com/w3c/gamepad).

**Comment by cvan** [comment]
<a href="https://github.com/toji"><img src="https://avatars.githubusercontent.com/u/805273?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [toji](https://github.com/toji)**
_Friday Apr 22, 2016 at 23:19 GMT_

----

FYI: I've proposed this and a couple other changes on the mailing list. http://lists.w3.org/Archives/Public/public-webapps/2016AprJun/0052.html

**Comment by mkeblx** [comment]
Gamepad Extensions:
https://w3c.github.io/gamepad/extensions.html

**Comment by cvan** [comment]
Closing in favour of the [Gamepad Extensions](https://w3c.github.io/gamepad/extensions.html) draft made by @toji. Thanks, @mkeblx!
