### ISSUE TITLE
Import as issues mailing list discussions (from web-vr-discuss + public-webapps)

### ISSUE THREAD

**Issue by cvan** [w3c/webvr#44]
I went through all the archives, plus my inbox, and here are the discussions I thought were relevant to API topics:

**[`[gamepad] Missing VRPose for tracked controllers`](https://lists.w3.org/Archives/Public/public-webapps/2016AprJun/0078.html)**
https://lists.w3.org/Archives/Public/public-webapps/2016AprJun/0078.html

**[`[webvr] [gamepad] Missing VRPose for tracked controllers`](https://mail.mozilla.org/pipermail/web-vr-discuss/2016-May/001108.html)**
https://mail.mozilla.org/pipermail/web-vr-discuss/2016-May/001108.html

**[`[webvr] Adding a VRPose to the Gamepad API`](https://mail.mozilla.org/pipermail/web-vr-discuss/2016-May/001109.html)**
https://mail.mozilla.org/pipermail/web-vr-discuss/2016-May/001109.html

**[`[gamepad] New feature proposals: pose, touchpad, vibration`](https://lists.w3.org/Archives/Public/public-webapps/2016AprJun/0052.html)**
https://lists.w3.org/Archives/Public/public-webapps/2016AprJun/0052.html

**[`[web-vr] Render Targets and WebVR`](https://mail.mozilla.org/pipermail/web-vr-discuss/2015-March/000608.html)**
https://mail.mozilla.org/pipermail/web-vr-discuss/2015-March/000608.html

**[`[webvr] Send multiple canvas to HMD`](https://mail.mozilla.org/pipermail/web-vr-discuss/2016-April/001080.html)**
https://mail.mozilla.org/pipermail/web-vr-discuss/2016-April/001080.html

**[`[webvr] Event to indicate hardware has requested VR presentation?`](https://mail.mozilla.org/pipermail/web-vr-discuss/2016-April/001096.html)**
https://mail.mozilla.org/pipermail/web-vr-discuss/2016-April/001096.html

**[`[web-vr] Proposing WebStereo`](https://mail.mozilla.org/pipermail/web-vr-discuss/2016-February/000990.html)**
https://mail.mozilla.org/pipermail/web-vr-discuss/2016-February/000990.html

**[`[web-vr] Proposed Verbiage change: Position => Pose`](https://mail.mozilla.org/pipermail/web-vr-discuss/2015-December/000936.html)**
https://mail.mozilla.org/pipermail/web-vr-discuss/2015-December/000936.html

**[`[web-vr] Spec questions`](https://mail.mozilla.org/pipermail/web-vr-discuss/2015-March/000610.html)**
https://mail.mozilla.org/pipermail/web-vr-discuss/2015-March/000610.html

<hr>

@anssiko recommends the following:

> I would probably just do that manually with credits to the original author. A new issue per mail, with a link to the mozvr mailing list archive. If there's a mail thread with relevant content, I might manually cherry-pick the substantial content from the thread to the issue. Anything goes, as long as we're clearly crediting the original author.

**Comment by anssiko** [comment]
Thanks @cvan. Anyone is free to take this task :-)

**Comment by cvan** [comment]
I think it's probably fine to keep those discussions on the mailing list. Feel free to discuss if folks feel strongly otherwise.
