### ISSUE TITLE
Replace offset by translation

### ISSUE THREAD

**Issue by D504** [w3c/webvr#47]
Suggestion: replace "offset" by "translation" ([here](https://w3c.github.io/webvr/#vreyeparameters)), or change type the "offset" attribute (Float32Array => float).

1) The "offset" attribute is a three-element array. It is Float32Array, but "offset" is distance, only number. 
It may cause misunderstanding.
2) "translation" is better name of the attribute than "eyeTranslation". Because it is eye property. Adding "eye" prefix is not needed.

**Comment by toji** [comment]
Offset is being removed in 1.2 completely in favor of explicit matricies
