### ISSUE TITLE
Updates to requestPresent to allow for 2 VRLayer's for devices that do separate texture per camera

### ISSUE THREAD

**Issue by DigiTec** [w3c/webvr#52]
Please refer to https://developer.microsoft.com/en-us/windows/holographic/rendering_in_directx and specifically the section on "Render to **each** camera".

The current VRLayer setup is optimized for rendering to a combined left/right eye surface. This means that a developer can too easily take a dependency on being able to render to both eyes at the same time simply by crossing over the texture center line. While this may not produce amazing results, it could be a dependency.

I'd like to extend VRLayer to take 2 layers, with the restriction that the VRSource objects for those layers are not the same and perhaps even that the bounds are the entire contents of the layer.

In combination with #51 this might mean adding a createDeviceLayers equivalent,

Note: These aren't final proposals, but mean to spur conversations.

**Comment by toji** [comment]
This is rendered somewhat moot by the current state of the explainer and the `multiview` attribute it exposes. Closing for now, but if you feel there's benefit to exploring alternate avenues to this I'm happy to reopen the conversation.
