### ISSUE TITLE
Test suites in scope?

### ISSUE THREAD

**Issue by anssiko** [w3c/webvr#53]
Currently, we have the following TBD text in the [Test Suites and Other Software][0] section of the charter draft inherited from the CG charter template:

>Test Suites and Other Software

>{TBD: State whether test suites or any other software will be created for any Specifications and list the relevant licenses. For information about contributions to W3C test suites, please see Test the Web Forward, and take note of the W3C's test suite contribution policy and licenses for W3C test suites. If there are no plans to create a test suite or other software, please state that.}

I'm aware of people who indicated interest in help with test suite creation, so unless I hear concerns, I'd suggest we update this section to say:

>Test Suites and Other Software

> The group MAY produce test suites to support the Specifications. The [W3C's test suite contribution policy][1] and [licenses for W3C test suites][2] apply.

[0]: https://w3c.github.io/webvr/charter/#test-suites
[1]: https://www.w3.org/2004/10/27-testcases
[2]: https://www.w3.org/Consortium/Legal/2008/04-testsuite-copyright.html

**Comment by cvan** [comment]
Yes, definitely. We'll likely be using some of @toji's [samples](http://toji.github.io/webvr-samples/), and we have a few of our own scenes that stress test WebVR. I will point interested folks to this thread. /cc @kearwood @dmarcos

**Comment by toji** [comment]
Worth noting that if we want real, actual, full stack tests of this thing it's going to involve robot arms in a data center somewhere with camera's strapped to them. :P We can definitely do tests that verify the API's completeness and run though some synthetic motions, though.

**Comment by anssiko** [comment]
Yeah, I think we want to be pragmatic, and start with IDL tests and synthetic motions. That said, I wouldn't mind if someone comes up with a testing framework that involves robot arms :P

I think #54 and #56 fixed this, so closing.
