### ISSUE TITLE
readonly attribute sequence<VRDisplay> activeVRDisplays; is invalid WebIDL

### ISSUE THREAD

**Issue by smaug----** [w3c/webvr#61]
http://heycam.github.io/webidl/#idl-attributes

" The type of the attribute, after resolving typedefs, MUST NOT be a nullable or non-nullable version of any of the following types:

    a sequence type
    a dictionary
    a union type that has a nullable or non-nullable sequence type or dictionary as one of its flattened member types
"

**Comment by kearwood** [comment]
The sequence has been changed to a FrozenArray in PR 49.
