### ISSUE TITLE
Exposing standard, monoscopic monitors as Display devices

### ISSUE THREAD

**Issue by capnmidnight** [w3c/webvr#63]
In [Primrose](https://www.github.com/NotionTheory/Primrose), it worked really well for my purposes to polyfill in the 2D monitor as a "VR Display" that had only one eye parameter. I returned those parameters when calling `getEyeParameters` with "left", and I passed null when calling with "right" (though see note on Magic Window configurations). I collect all non-null eye parameters into an array and then I loop over that array as I render. The `requestPresent` method polyfilled to calling the standard Full-Screen workflow.

Because of this, I didn't have to create special code paths to handle the technically-only-marginally-different types of displays. There's only one path of code for displays. And to support spectator mode--showing a mono rendering on the monitor--I could theoretically only have to create an array of displays over which to loop. Such a setup should also be more future-proof against CAVE setups.

As opposed to how webvr-polyfill works, I also didn't implement touch-panning or mouse/keyboard movement in that display for the same reason: it would create two code paths for handling input. I already support mouse/keyboard for desktop users on tethered HMDs, and touch-panning is also useful for non-stereo use-cases with tablets in Magic Window configurations.

**On Magic Window configurations:** technically, a smartphone is capable of both Magic Window and Google Cardboard, but it's not multiple displays, it's just multiple rendering configurations for one, common display. So instead of returning a mono-display configuration through one-of "left" or "right" from getEyeParameters, it probably makes sense to have a completely separate "eye parameter" for "center" or "mono".

I'm using webvr-polyfill now because I got tired of trying to keep device fusion working in my configuration, so I don't have that feature in my current DEV branch anymore, but you can see it in the master branch (and thus, on [primrosevr.com](https://www.primrosevr.com)) right now as I don't have the new deployment ready yet. I will probably end up polyfilling the concept back in, either by trying to get webvr-polyfill to adopt the idea, forking webvr-polyfill, or pre-wrapping navigator.getVRDisplays before webvr-polyfill can get to it.

**Comment by toji** [comment]
I agree that this can be useful for development, but it seems like the realm of dev tools or polyfills rather than the API/spec. In fact, the [WebVR Emulator](https://chrome.google.com/webstore/detail/webvr-api-emulation/gbdnpaebafagioggnhkacnaaahpiefil) seems like it covers this use case reasonably well.

**Comment by cvan** [comment]
I understand the use case, and I share your desires wholeheartedly. I do agree with @toji with having this covered by the WebVR Emulator, @borismus' [`webvr-polyfill`](https://github.com/borismus/webvr-polyfill), or some other "polyfill" library. Feel free to start a library - or fork the `webvr-polyfill` to make this happen. (We could probably get quite a few interested parties to contribute, I'd think.)

**Comment by capnmidnight** [comment]
Well, in the case of eventually supporting CAVE setups, you'll need to be able to directly address different mono displays separately and distinctly. WebVR gives us the ability to address certain stereo displays directly, but not the flat ones. I didn't mean this in terms of a feature for testing, I meant it as a user-facing feature. It even goes beyond VR: maybe people playing standard games or watching videos want to run on a display other than their primary display. In these cases, it's not something the app developer would be able to polyfill, the browser would have to provide some new API-level access.

**Comment by toji** [comment]
In the case of a CAVE setup or similar, I think WebVR could support it as-is with one minor tweak: Have more than two eyes. If `getEyeParameters` could accept `left`, `right`, `front`, `back`, `top`, and `bottom` each could report the appropriate frustum (which may look a bit weird, but should work) and offset (which is already 3D).

**Comment by capnmidnight** [comment]
Okay, I made a separate project out of it: https://github.com/NotionTheory/webvr-standard-monitor

It works stand-alone, or it can work around WebVR-Polyfill or native WebVR API to provide a "Magic Window" view on mobile devices.
