### ISSUE TITLE
Description of pose returned by getPose() is confusing

### ISSUE THREAD

**Issue by kearwood** [w3c/webvr#65]
I propose we change the description of the getPose() return value to be easier to understand and more concise:

From:
The pose returned MUST NOT change until JavaScript has returned control to the browser.

To:
Subsequent calls to getPose() MUST return a VRPose with the same values until the next call to submitFrame().

**Comment by kearwood** [comment]
Additional text should be added to getImmediatePose() as well to help differentiate them:

Every call to getImmediatePose() may return a different value, even within a single frame.

**Comment by toji** [comment]
LGTM, though Chrome's implementation extends the limitation beyond the submitFrame call and to the end of the callback. That would be allowed under this language, I think.
