### ISSUE TITLE
Need to describe if (or if not) VRDisplay.stageParameters can change between null and non-null after VRDisplay enumeration

### ISSUE THREAD

**Issue by kearwood** [w3c/webvr#67]
Need to describe if (or if not) VRDisplay.stageParameters can change between null and non-null after VRDisplay enumeration.

I propose that we add text to the description of the stageParameters attribute:

  /**
   * If this VRDisplay supports room-scale experiences, the optional
   * stage attribute contains details on the room-scale parameters.
+   *
+   * The stageParameters attribute can not change between null
+   * and non-null once the VRDisplay is enumerated; however,
+   * the values within VRStageParameters may change after
+   * any call to VRDisplay.submitFrame as the user may re-configure
+   * their environment at any time.
   */
  readonly attribute VRStageParameters? stageParameters;

**Comment by toji** [comment]
LGTM. `stageParameters` tend to be something you know the device _can_ support at instantiation, even if it hasn't initialized to the right values yet.
