### ISSUE TITLE
Need to describe time-base of VRPose.timestamp 

### ISSUE THREAD

**Issue by kearwood** [w3c/webvr#68]
In order to prevent incorrect usage of the  timestamp attribute of VRPose, the time-base should be described in more detail:

file:///Users/kearwood/dev/webvr-spec/index.html#vrpose-state-attributes

I suggest adding text to the end of timestamp's description:

The time-base of timestamp is only guaranteed to be consistent for one VRDisplay instance. The timestamp attribute should not be used to determine the chronological order of VRPose's from separate VRDisplay's or compared with timestamp values outside of VRPose.

**Comment by bzbarsky** [comment]
The best way to guarantee this is to use as 0 the time the VRDisplay was created or something...

**Comment by toji** [comment]
LGTM.

I've heard a lot of talk about using timestamps for sync between video/audio/VR streams but there's a lot more work that needs to happen from multiple specs for that to be feasible. We shouldn't block on figuring it out. Declaring that these are consistent only for a given display gives us some good wiggle room to define something that's meaningful for the individual device while still allowing us to tighten down the spec later to something more closely integrated with the browser's media stack.

**Comment by bzbarsky** [comment]
Declaring something in a spec means absolutely nothing in terms of what sites do.  So if you declare that they must not be compared but all browsers give them the same zero time (e.g. Unix epoch, which is what Firefox is doing right now), sites _will_ start to depend on it.  And then you will not have any wiggle room at all.

**Comment by kearwood** [comment]
It should be possible to implement 0 as the time the VR Display was created by storing the value that would have been used as the timestamp value of the first pose returned and then subtracting this from any timestamp values that are returned afterwards.

**Comment by dmarcos** [comment]
@kearwood Is the comment you suggested still appropriate? Or we should include in the spec that the timestamp starts at 0 the first time `getPose` is invoked for a given display?

**Comment by kearwood** [comment]
@dmarcos I agree with your summary.  Essentially the timestart would start at 0 the first time getPose is invoked for a given display.
