### ISSUE TITLE
VRDisplay.requestPresent should throw when VRLayer.source is null

### ISSUE THREAD

**Issue by kearwood** [w3c/webvr#72]
I propose that we continue to allow VRLayer.source to be a null value, with the expectation that future extensions to VRLayer will perhaps define new kinds of layers that do not require a source value.

Perhaps VRDisplay.requestPresent should throw when it does not have enough information to create a valid VRLayer.  This would imply that until there are additional attributes to define new layer types, that VRDisplay.requestPresent would throw when VRLayer.source is null

**Comment by toji** [comment]
I like framing the requirement like that, because a "valid VRLayer" may mean a lot of things in the future. The presence or lack of a particular attribute isn't necessarily a reason to fail.
