### ISSUE TITLE
Adverse effects of webvr 1.1 shim on non WebVR browsers (Desktop)

### ISSUE THREAD

**Issue by jbroberg** [w3c/webvr#84]
As mentioned on the WebVR slack, I'm getting:

webvr-1-1.js:209 Uncaught TypeError: Cannot read property 'fieldOfView' of null ; (line 208/209) 

when dropping the webvr-1-1 shim into my existing project.

**Comment by toji** [comment]
I believe this has been fixed. Closing to clean up issue tracker and focus on spec changes.
