### ISSUE TITLE
 FrozenArray<VRDisplay> for activeVRDisplays doesn't work if activeVRDisplays can change

### ISSUE THREAD

**Issue by foolip** [w3c/webvr#85]
https://heycam.github.io/webidl/#idl-frozen-array

"A frozen array type is a parameterized type whose values are references to objects that hold a fixed length array of _unmodifiable_ values." (my emphasis)

If the active displays are always known synchronously, then a `sequence<VRDisplay> getActiveVRDisplays()` would work, otherwise a promise I guess.

**Comment by NellWaliczek** [comment]
I'm a bit confused here as well. 

And relatedly, looking at that same documentation, for sequence<T>, i see the following:

> Sequences are always passed by value. In language bindings where a sequence is represented by an object of some kind, passing a sequence to a platform object will not result in a reference to the sequence being kept by that object. Similarly, any sequence returned from a platform object will be a copy and modifications made to it will not be visible to the platform object.

I'd been assuming that this is saying that modifications to the sequence returned by getVRDisplays() will not be visible to the platform object, but that modifications to the VRDisplay objects themselves will be.

As for the FrozenArray<VRDisplay>, it would be great to get confirmation from @toji or @kearwood about the intent.

**Comment by foolip** [comment]
Actually, I was wrong, `FrozenArray<VRDisplay>` can work, it's just that the attribute will sometimes start returning a new value. https://github.com/whatwg/html/pull/1860 is an example of how you might phrase it.

With no prose around this at all, a test checking that `navigator.activeVRDisplays === activeVRDisplays` would have no basis in the spec, and that would be sad.

Even though FrozenArray can be used, it still might be less trouble to just have a method, but take a pick. @domenic, do you there's a reason to pick one pattern or the other?

**Comment by domenic** [comment]
Both are OK. Probably in this case a frozen array makes more sense since I imagine the number of VR displays won't be changing often, and returning a mutable array isn't useful for web developers (e.g. there's no use case where you want to push to or pop from the array before handing it off to some other code).

**Comment by toji** [comment]
`activeVRDisplays` has been removed from the current version of the spec, so this is no longer an issue. We'll keep the behavior of FrozenArray in mind if we use it in the future, though.
