### ISSUE TITLE
What does Gamepad's displayId return, how is it set?

### ISSUE THREAD

**Issue by foolip** [w3c/webvr#87]
https://w3c.github.io/webvr/#interface-gamepad

The spec doesn't say how to associate a `Gamepad` with a `VRDisplay` or what `displayId` returns if they're not associated.

**Comment by foolip** [comment]
Oh, from that change I take it this is about grouping a `VRDisplay` that's somehow physically related with or connected to a `Gamepad`, not about associating (whatever that would mean) an arbitrary `Gamepad` with a `VRDisplay`?

In that case, I wonder if `Gamepad` can't simply have a `readonly attribute VRDisplay? display` or similar, instead of the indirection of an id?

**Comment by toji** [comment]
Not a bad idea. I'll bring it up on the implementors call today.

**Comment by NellWaliczek** [comment]
Given that the getVRDisplays() call is returning a promise, do we want to take a dependency on the VRDisplays being already available at the time the gamepads are queried?

Get Outlook for iOS<https://aka.ms/o0ukef>




On Tue, Sep 20, 2016 at 12:53 PM -0700, "Brandon Jones" <notifications@github.com<mailto:notifications@github.com>> wrote:


Not a bad idea. I'll bring it up on the implementors call today.

-

**Comment by toji** [comment]
It's been my experience thus far that any gamepad for which this attribute would be used can't reasonably be detected until the API for the related VR system is initialized (and some don't show up at all until the VRDisplay is presenting.) As such it's probably not unreasonable to say that the device must have already been made available before the gamepad can be accessed.
