### ISSUE TITLE
Do any of VRLayer's members need to be nullable?

### ISSUE THREAD

**Issue by foolip** [w3c/webvr#89]
https://w3c.github.io/webvr/#interface-vrlayer

It rather seems like source should be required and non-nullable, and that the `sequence<float>` attributes can just be non-nullable, given that they already have `[]` default values.

**Comment by foolip** [comment]
If `source` isn't required, then `requestPresent()` would have to handle that case.

**Comment by toji** [comment]
Layers have been significantly restructured in the [current explainer](https://github.com/w3c/webvr/blob/master/explainer.md#setting-up-a-vrlayer) which largely renders this issue moot. Closing.
