### ISSUE TITLE
VRLayer.leftBounds and VRLayer.rightBounds should not allow null

### ISSUE THREAD

**Issue by kearwood** [w3c/webvr#95]
There is ambiguity between setting a null value and an empty array to the leftBounds and rightBounds attributes.

We can remove the nullability and default the value to an empty array to remove the ambiguity.

dictionary VRLayer {
  VRSource? source = null;
  sequence<float>? leftBounds = [ ];
  sequence<float>? rightBounds = [ ];
};

Should become:

dictionary VRLayer {
  VRSource? source = null;
  sequence<float> leftBounds = [ ];
  sequence<float> rightBounds = [ ];
};

This change has already been implemented in Firefox and the change was not propagated to the spec here.

**Comment by kearwood** [comment]
Added PR #96

**Comment by toji** [comment]
Totally agreed. PR merged.
