### ISSUE TITLE
WebGLTexture as a VRLayer source

### ISSUE THREAD

**Issue by brianchirls** [w3c/webvr#99]
I'd like to consider the ability to present directly from a `WebGLTexture` rather than having to present only from a canvas. I don't know how easy or efficient a browser implementation would be, and it would certainly be more valuable once WebGL2 is available so you can use antialiasing. But it would solve at least a couple potential problems:

1) Right now, you need to make the canvas as big as the resolution of the HMD, even if you don't need it that big on the page. If you can present from a texture, you can keep the canvas whatever size you want it and size the texture independently.

2) You'll be able to de-couple the screen rendering frame rate from the HMD frame rate. As it stands, an HMD may need to render at 90fps but the screen only refreshes at 60. But since you're presenting the canvas, you have to re-render the screen view over the HMD view after every frame. If you can present from a texture you don't have to do that. You can render the screen only every 60 frames, or even less. You can use the extra time in between frames to run some AI or physics or just reduce energy usage.

**Comment by mkeblx** [comment]
Interesting, could be useful. Reminds of using an offscreen canvas for WebVR (plus extra benefits of ability to do in a worker) discussed a ways back and in spec as a `VRSource`. https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas

For 1) can't you resize canvas using CSS so page size and canvas dimensions independent? Scaling should not be an issue.

For 2) I think there's a way currently to decouple, maybe like this? A 2d canvas that copy render into at 60/whatever Hz. Could do with one canvas if really have to I think.

```js
var frameData = new VRFrameData();
var mirror = true;
var renderMirror = true;
var desiredRate = 1000 / 30;
var lastTime = 0;

var webglCanvas = renderer.domElement;
var canvas = document.getElementById('screen-canvas');
var ctx = canvas.getContext('2d');

// could do with delta timer as well.. 
// would be easier for setting desired framerate
window.requestAnimationFrame(function screenRAF(t){
   renderMirror = true;    
   window.requestAnimationFrame(screenRAF);
}) 

// 60/90Hz, native if presenting
vrDisplay.requestAnimationFrame(function vrRAF(t){
  var deltaTime = t - lastTime;
  lastTime = t;

  vrDisplay.getFrameData(frameData);
  if (vrDisplay.isPresenting) {
    renderVR(frameData);
    vrDisplay.submitFrame();
  }

  if (mirror && renderMirror) { // 60Hz
    renderScreen(frameData);
    renderMirror = false;
  }

  vrDisplay.requestAnimationFrame(vrRAF);
});

function renderScreen(frameData) {
  renderer.render(scene, screenCamera);
  ctx.drawImage(webglCanvas, 0, 0); // performant?
}
```

**Comment by toji** [comment]
The current API detailed in the explainer has moved away from using the Canvas default backbuffer to a framebuffer provided by the API. This gives the UA a lot of avenues for optimization and allows it to opaquely set up the buffer with the best format. Separately we're considering more explicit mechanisms for mirroring. This should handle the concerns that @brianchirls cited. Closing.
